### ISSUE TITLE
Comments: strange glitch when doing edit -> cancel -> edit

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1047]
Go through the following flow:
+ create a comment with one word in it
+ edit the same comment, adding a second word
+ go in edit mode again, but now press Cancel
+ click edit a third time: the second word seems to be gone
+ clicking cancel again makes the second word reappear, but I'm also able to edit the comment as if the second word was not there. Saving that would make me lose the second word

**Comment by iteles** [comment]
@asimonw Thanks for raising this.

As @SimonLab and @Danwhy are working on #935 today, if @Cleop has some time after she has completed https://github.com/emfoundation/ce100-app/issues/947#issuecomment-341672911, she'll take a look at this next 👍

**Comment by Cleop** [comment]
@SimonLab @Danwhy - I've taken a brief glance at this and wanted to run past you my thoughts.

I've isolated the behaviour down to the cancel and edit buttons (no need for creating a new comment). Editing works fine on its own when done multiple times using ajax. **The cancel button seems to be disrupting the edit ajax functionality**. So...

If you edit a comment via ajax and then go to edit it again, press cancel, and then go to edit it again, the editing box will contain text from the original comment prior to any of your ajax editing. 

The saved comment (when you go out of edit view) is as it should be throughout. It's only the text displayed in the editing box which is out of kilter.

I suspect that whilst the cancel button works using ajax, it is always 'cancelling' or cleaning back to a pre ajax state. So we need to amend it so that it can pick up on the latest ajax version, not the last refreshed version and that way this info can be fed into the edit box.

**Comment by iteles** [comment]
Continued as of tomorrow in sprint 10.
