### ISSUE TITLE
filter organistions by tags (from the API)

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#1088]
Organisations can be filtered by tags and locations:
- [x] update the list of tags and location
- [x] update the queries to search for tag or location

**Comment by asimonw** [comment]
@SimonLab After selecting a location tag on the org view in Explore, if I then switch to the challenges or insights tab, the location filter is not maintained. The tag selector says "All tags" instead of the tag that was selected, and a message "Nothing matches your search criteria" is displayed, even when I know that there should be matches.

Something similar happens when going from challenges to orgs.

**Comment by SimonLab** [comment]
@asimonw I've redeploy the most recent version on the test app https://ce100-test.herokuapp.com/orgs?locations=1
This branch also now contains the last UI changes done by @Cleop

**Comment by asimonw** [comment]
@SimonLab That seems to have solved it!
