### ISSUE TITLE
Use more specific API endpoints to retrieve insights and resources

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1108]
There are two specific endpoints corresponding to insights and resources:
+ Insights: `/api/assets/collection/1`
+ Resources: `/api/assets/collection/2`

It would be more future proof to use these endpoints rather than the generic `/api/assets` because the DAM will include more and more collections serving other applications over time.

**Comment by SimonLab** [comment]
This is now deployed on  ce100-test, I think this issue is "technical" so I think the only way to test this is to check the code is calling the correct api when getting insights/ressources:
- we first call a function in the handlers to get assets by  a specific category
https://github.com/emfoundation/ce100-app/blob/c3ce1aec2b35c252ac2d79f2b3d495756956c5e6/server/handlers/insights/browse-insights.js#L15
https://github.com/emfoundation/ce100-app/blob/c3ce1aec2b35c252ac2d79f2b3d495756956c5e6/server/handlers/insights/browse-resources.js#L11

- This function will then call the correct endpoint:
https://github.com/emfoundation/ce100-app/blob/c3ce1aec2b35c252ac2d79f2b3d495756956c5e6/server/dam-api/api.js#L63-L65

**Comment by asimonw** [comment]
@SimonLab I cannot test the exact endpoint you're using, but tested that the correct assets are still retrieved for insights and resources 👍
