### ISSUE TITLE
Update main navigation

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1152]
All items relating to the logged in person will be grouped under the same link in the top nav:
+ My profile
+ New challenge (not present for internal roles)
+ My organisation (not present for internal roles, pulled out in top nav on desktop)
+ Settings
+ Log out

Other items will be reorganised a bit accordingly. On mobile, a bottom nav will remain for the time being, containing links to
+ Home (currently the walk through, but later on the dashboard)
+ Explore
+ Search
+ More (which links to Resources and Contact)

The home button is not present for internal roles. The fourth item in the bottom nav will instead be the already present "+ Add new" button.

On desktop these items will remain available at the top, more or less as they are now.
Links to People will move into Explore (see #1153 )

FYI: the rationale for having a home button for external/frontend roles vs "Add new" for internal/backend roles, is that this will most likely evolve into a dashboard link for all roles. This dashboard will have different functionality for internal and external roles.

**Comment by iteles** [comment]
Estimate TBC, awaiting further details.

**Comment by Cleop** [comment]
@asimonw @fannyBkane assuming that secondary users will now have the same nav as primary users given that: 
>  Both primary and secondary users can create challenges
from #1147 so the:
<img src="https://user-images.githubusercontent.com/16775804/33661554-58b340c4-da80-11e7-8762-192ab917871f.png" width=150px />
will show for both.

**Comment by fannyBkane** [comment]
@Cleop that's right. 

Worth mentioning here that we're rethinking the nav so the +challenge link is likely to move into a burger menu, TBC.

**Comment by fannyBkane** [comment]
The desktop and mobile prototype show the admin nav, as well as links to specific pages that will be available to primary users (Add new challenge, link to org)

This is in order to show as many features on the prototype as possible.

The nav for primary users (non admin) would be as follows:
![screen shot 2017-12-07 at 12 04 11](https://user-images.githubusercontent.com/20577339/33714419-c4ade1a0-db46-11e7-8b5b-8e7a967eaa4d.png)

**Comment by asimonw** [comment]
**Also good to note:** admins will not have the home button in the footer nav, but they will have the "+ Add new" button which is already present currently instead.

**Comment by asimonw** [comment]
@fannyBkane No need to redo the mockups for this, but we had been adding a logout link straight into the user nav in previous iterations. I quite liked that (it's also a very common pattern), so could we add that both for all user roles?

**Comment by fannyBkane** [comment]
that's fine @asimonw

**Comment by Cleop** [comment]
## Notes to self:
**Admin - Desktop**
![screen shot 2017-12-08 at 11 50 06](https://user-images.githubusercontent.com/20577339/33764822-115b004c-dc0e-11e7-8c60-51687f8f8fb2.png)
![screen shot 2017-12-08 at 13 38 54](https://user-images.githubusercontent.com/20577339/33768355-8d709f2a-dc1d-11e7-98a7-1c2e286dddbf.png)
![screen shot 2017-12-08 at 12 06 12](https://user-images.githubusercontent.com/20577339/33765342-3fad531c-dc10-11e7-8182-57824bc2d308.png)

- [ ] Change copy from 'Add' to 'Add New'
- [ ] **Reverse colours of dropdown menu on desktop only to white background and blue text**?
- [ ] **Revise the width and positioning of the dropdown menus?**
- [ ]  Add profile photo onto top nav
- [ ]  **Rotate 3 dots ellipsis to be horizontal not vertical?**
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by Cleop** [comment]
@fannyBkane - thanks for sharing the designs. I have now begun working on them to get a feel for how they fit together and how long it may take to complete. I am aware that this issue is currently the highest priority for this sprint and that we only have a few days remaining. Given the size of the issue and its position in the priority list I wondered if it may be easier to divide the changes up between structural changes and visual enhancements? This way we can ensure that this issue doesn't block progress on other issues if some parts of it are less important than others.

**These are changes that I would classify as visual enhancements:**
- Replace the ellipsis with a horizontal ellipsis (new asset required)
- Putting the user's name on the full page menu on mobile when it's open and moving the profile photo to the left
- Restyling the dropdown menus on desktop to be white with blue text, giving them round edges and a different border colour.
- The dividing line between Settings and logout on the full page mobile menu

**Questions I have that would be great if you could confirm/ clarify:**
- Should selected / hovered nav items still have the light blue underline?
- Should there be 'logout' on this menu as the screenshots above feature it but invision doesn't currently? And should the dividing line be there too?
![image](https://user-images.githubusercontent.com/16775804/33936659-2c45fc02-dff8-11e7-9316-e9ac88c3e2c2.png)
- Should all of the bottom navbar items have inverted colours when they're selected?

**Comment by fannyBkane** [comment]
Hey @Cleop to split up the changes, and the list you wrote up make sense.

To answer your questions

- The selected / hovered nav items should keep the underline. But is it possible to remove it for the Search magnifying icon (and instead have a 10% darker hover state)?
- There should be a logout on the menu. The dividing line can be built in later, as long as the logout is of a different colour

I will update the screens on Invision.

I hope it makes sense.

**Comment by Cleop** [comment]
@fannyBkane - please can you email me the asset for 'My organisation' in the navbar, it's 3 people figures. Thank you!

**Comment by fannyBkane** [comment]
✅

**Comment by Cleop** [comment]
Amending the time estimate. The design involves manipulation of the intercom package because one of the new bottom navbar menus needs to sit on top/ in front of the intercom button. This will require some extra work so that we can override the !important styling on the z-index of the intercom item in this instance.

**Comment by Cleop** [comment]
@fannyBkane - please can you provide the home icon for mobile view? Thank you 😄

**Comment by fannyBkane** [comment]
@Cleop emailed it!

**Comment by asimonw** [comment]
@Cleop I know that this is not in pleas- test yet, but I just noticed that the bottom nav on mobile is still the old one for secondary users. This should be the same as for primary users.

Also, the items of the "more" menu for primary users are wrong (they are what used to be the options for admins in the "+ add" menu). Just so you know :)

**Comment by iteles** [comment]
Only thing left to do here is ensure that the 'Explore' button remains highlighted when users click onto the 'People' tab in the explore view.

![screen shot 2017-12-19 at 10 29 32](https://user-images.githubusercontent.com/4185328/34153454-048a35c8-e4aa-11e7-9c52-6e72a320aeeb.png)

Intercom issue moved to #1199

**Comment by asimonw** [comment]
@iteles @Cleop Note my https://github.com/emfoundation/ce100-app/issues/1152#issuecomment-352780984 as well.

**Comment by fannyBkane** [comment]
@Cleop @asimonw lgtm

**Comment by asimonw** [comment]
@Cleop The issue mention in https://github.com/emfoundation/ce100-app/issues/1152#issuecomment-352782612 is still there. On mobile, Explore is not highlighted in the nav when on the People tab.

On mobile, the Contact us link is also still wrong. It still leads to the "add user" page, rather than the required mailto link.
