### ISSUE TITLE
Add People and Resources to Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1153]
We would like to add two more tabs to Explore. Even though these tabs will not work with the tag/location filter, it feels more natural to bring these together.

This means that when people select one of these two tabs, the filter will be accompanied be a message saying that the filter is not available for the selected tab and the filter itself will be disabled.

To be discussed: when a filter is already selected, what should happen when someone selectes one of these two tabs:
+ the filter is cleared
+ the filter is maintained, but has no effect on the selected tab. When the user returns to another tab which supports the filter, the previously applied filter is still in effect.

UPDATE:
+ We decided that only People will be added to explore (because Resources will never be tagged and are less important to the app).
+ We'd like to go for scenario 2 above: maintain filter state when switching to the People tab, but with a message "Filter by tag not available"
+ To keep things simple until People are also tagged, we will not yet update the title to reflect the current filter. The title will be "Explore" for all tabs and filter states, as it is now.

**Comment by fannyBkane** [comment]
[Link to Invision - Desktop](https://projects.invisionapp.com/d/main#/console/12767821/267419073/preview)
![screen shot 2017-12-05 at 09 44 10](https://user-images.githubusercontent.com/20577339/33600358-e9bad270-d9a0-11e7-8f98-249956847fc6.png)

[Link to Invision - Desktop](https://projects.invisionapp.com/d/main#/console/12767821/267419071/preview)
![screen shot 2017-12-05 at 09 45 28](https://user-images.githubusercontent.com/20577339/33600408-0fd3112a-d9a1-11e7-9ebc-e34912dcee2c.png)

**Comment by fannyBkane** [comment]
[Link to horizontal swipe component on mobile](https://www.thinkdif.co/schedule) on the DIF website. You will see that the scroll is infinite here. 
We don't know how well it worked for users. So, we'll check the user data and update the issue.

**Comment by iteles** [comment]
@asimonw Our time estimate here is for the _desktop_ portion of this issue.

For mobile we still need you and @fannyBkane to finalise the expected behaviour.
How would your users feel about us swapping out the _words_ in the tabs for _icons_ on mobile?

e.g. something like http://fontawesome.io/icon/users/ for organisations, http://fontawesome.io/icon/lightbulb-o/ for insights, etc

**Comment by asimonw** [comment]
@iteles Top comment and visual (for Desktop) updated. We will think about your suggestion for mobile 👍

**Comment by fannyBkane** [comment]
Added icons to the 'Explore' tab menu, which means that the 4 tabs should now fit on the smallest phone screen, and no longer require a horizontal swipe.

Please note that, in order to fit icons and tiny text nicely within the toggle tab element, it required to tweak the padding top and bottom. I also increased the margin top and bottom of the filter.

Please see specs [here](https://projects.invisionapp.com/d/main#/console/12795181/267955221/preview#project_console)

In



![screen shot 2017-12-07 at 17 31 44](https://user-images.githubusercontent.com/20577339/33729152-aaff7e2a-db74-11e7-8fff-1ae9cecc82bc.png)

**Comment by Cleop** [comment]
@fannyBkane - please can you provide the challenge, insight and people assets for this?

**Comment by fannyBkane** [comment]
Sent by email.

**Comment by Cleop** [comment]
@fannyBkane - where are we supposed to put the 'sort by' functionality for the people tab?

**Comment by fannyBkane** [comment]
@Cleop yes let's do that for now.

**Comment by asimonw** [comment]
LGTM!
