### ISSUE TITLE
The add org/user button is not visible in the nav for content owners

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1218]
A content owner should be able to create orgs and users (all user types but admins). Currently, the Add org/user button in the main nav is not visible except when the user is on the Explore Organisations tab. For other tabs in Explore (and most other pages), the Add button is not visible:
<img width="1136" alt="screen shot 2018-01-03 at 17 12 59" src="https://user-images.githubusercontent.com/15235804/34528737-1fef6f02-f0aa-11e7-9fec-1912169bf923.png">

**Comment by Cleop** [comment]
In addition to this, it appears that the bottom nav menu is really missing when logged in as a content owner on mobile: 
![image](https://user-images.githubusercontent.com/16775804/34731458-49e97000-f55a-11e7-9e3d-1569b3302a99.png)

Again, it works fine when you're on the organisation tab on mobile. It's when you move to the other tabs.

**Comment by asimonw** [comment]
@Cleop Nice spot! Would be great to fix that as well :)

**Comment by SimonLab** [comment]
The permissions object which contains the information which allow the template engine (Handlebars) to display the right UI depending on the type of the logged in user is defined in the pre-handler, e.g.
https://github.com/emfoundation/ce100-app/blob/ad47e141854392ba3d297dab902b5e11684783a0/server/routes/orgs.js#L68

This object is define by the following function:
https://github.com/emfoundation/ce100-app/blob/ad47e141854392ba3d297dab902b5e11684783a0/server/routes/permissions/get-permissions.js#L1-L18

So instead of checking for ```permisions.admin``` in the templages we need to use ```permissions.backendUserAdmin``` which is true if the loggedin user is an admin or a content-owner.
