### ISSUE TITLE
organisation_id and primary_id default set to '' but sent as -1 in tests

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#127]
At the moment, in a user object, we store `organisation_id: ''` as the default. In the tests you wrote on Sunday, I think -1 represents a 'default' or 'no organisation currently linked'. Is that right? I don't think the handlebars represents that change.

Same also applies for primary_id in an organisations data set. 

I like the -1, is there any disadvantage of changing the default to -1 in setup-data.js and in our handlers initialiser helper function? It seems to make sense to keep it as a number throughout. 

Relates to #38 .

**Comment by mk4111** [comment]
Hi @JMurphyWeb :) 

You're right - I haven't changed any of the mock data for organisations, as that wasn't the userflow I was working on at the time. 

'-1' is meant to represent 'no organisation currently linked' and was chosen because the value is (currently) deemed valid if it is of type number. 

I think some of our tests and handlers rely on the bool ```organisation_id === true || false``` to execute, so I think that's something we should check. Definitely up for changing that though, because it's better to keep things consistent and I think we both agree this is something we need to unify to either or.

**Comment by JMurphyWeb** [comment]
now in master
