### ISSUE TITLE
Design: improve list behaviour

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1335]
As a CE100 contact I want to filter, sort or group items in long lists, so I can more easily find items that interest me or that I already know should be there

**Comment by fannyBkane** [comment]
Hey @asimonw @Kimberley-Heath Besides seeing what is the latest, we don’t have insights about how cello users want to filter, group, or sort items. 

In order to make a logical step forward to learn more about it, I asked you both for input, and also looked at cello, and did some research on the web. I collated our options in a table. 

![screen shot 2018-06-04 at 16 13 00](https://user-images.githubusercontent.com/20577339/40925701-3abd757e-6812-11e8-8b8b-d12bcfacdd2e.png)

Bear in mind this is taking into account any useful way of sorting/filtering, regardless of whether cello can currently do it or not...   

Does this make sense? Anything missing? 

Next, those will be prioritised based of what we most want to learn, and what makes most sense from what we have already and technical challenges. 

Thank you!
