### ISSUE TITLE
Add a sort option to all tabs in Explore

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1376]
To improve handling long lists, we'd like to add a consistent way to sort lists in Explore as is already present for People.

**Acceptance criteria**:
- [x] sort organisation by "A-Z" or "Z-A"
- [x] sort challenges by "Newest" or "Oldest"
- [x] sort insights by "Newest" or "Oldest"

[Link](https://invis.io/DYESHUZW7#/300141938_Explore_People) to desktop prototype

**Comment by Danwhy** [comment]
Clarified in sprint planning: This is for desktop only, sort is hidden on mobile

**Comment by fannyBkane** [comment]
[Link](https://invis.io/DYESHUZW7#/300141938_Explore_People) to desktop prototype

**Comment by sophielevens** [comment]
Hi @fannyBkane, in the mockups you've given us here the "sort by" dropdown is styled differently to what we currently have on the designs. Is this intentional?

Current design: 
![image](https://user-images.githubusercontent.com/25961258/41410105-424db66c-6fd0-11e8-8ade-1911558fac09.png)

Mockups above: 
![image](https://user-images.githubusercontent.com/25961258/41410131-547de9b0-6fd0-11e8-867e-9b04cf26d644.png)

Thanks 👍

**Comment by fannyBkane** [comment]
Hi Sophie, it's intentional. But indeed it was not part of this issue. So I have just created #1403, to be prioritised @asimonw if that's ok?

**Comment by asimonw** [comment]
@sophielevens Indeed, keep the styling as it is for now and we'll address the style change in #1403

**Comment by fannyBkane** [comment]
LGTM @sophielevens @Danwhy @asimonw
