### ISSUE TITLE
Simplify onboarding flow

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1390]
**UPDATE**: further simplification of onboarding flow:

- [x] The  `/choose-interests` screen should merge with the `/matches` screen
- [x] This new screen has three potential states
  - No interests are detected for that user: show the contents of what used to be `/choose-interests` (state 1) [mockup](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298354399)
  - Interests detected,  but no matches were found: contents of `/matches` when no matches are found is shown (state 2) [mockup](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/299074280)
  - Interests and matches found: contents of what used to be `/matches` is shown (state 3) [mockup](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298354397)
- [x] The new "merged" page should live at `/`
- [x] This is the first page primary and secondary users see after logging in (and after going through the consent screens if necessary), and for those users the cello logo (top left) should also link there (for internal users, this remains Explore)
- [x] We no longer need the walk through screen (can be removed, but an equivalent screen might return in a different context in the future)
- [x] Onboarding flow:
  - After the consent flow, the user sees state 1. Note that the "Skip" button is changed to "Explore cello", which should link to Explore
  - After the user selects their interests, they are taken to state 2 or 3 (depending on whether matches were found). Note that some extra text is added underneath the banner title, and that the copy and buttons at the bottom of the screen have also been changed. In particular, there is only one button now, "Go to settings", which links to the personal setting page (no longer opens the interest selection modal directly).
  - If the user chooses to go to their personal settings from there, clicking save should take them back to the matches page. In general, could it be such that saving personal settings always takes you back to the page you came from? (usually matches or profile).

**Comment by asimonw** [comment]
@sophielevens please let me know if the updated scope for this issue poses any problems. In particular, is the impact of changing what's on `/` easy enough to control?

@fannyBkane @Kimberley-Heath let me know if anything in this issue doesn't make sense.

**Comment by Kimberley-Heath** [comment]
@Danwhy so I tested this and there are a couple of things I have noticed:

- [ ] 'Go to settings' button on My Matches links back to their profile rather than their personal settings
- [ ] If you go into their settings and open the tag modal and deselect some interests/ add some interests and click add, the button does not close the modal or save the changes.
(should the 'add' button say 'save' if they just want to deselect some interest tags/edit rather than add @asimonw or are we still discussing the right word?)

**Comment by asimonw** [comment]
@Danwhy Actually, @Kimberley-Heath 's second point was already raised in #1317 and the last one should also be solved when the cancel problem raised in that issue is solved.

So only the first point needs to be considered here.

**Comment by asimonw** [comment]
@Danwhy Looks good now.

Two questions @fannyBkane and @Kimberley-Heath:
- the "your interests" state of the screen (when no interests were shared yet) doesn't have any nav on mobile, but it does on desktop. I think having a nav makes sense (also on mobile) because people can navigate back to the page from anywhere in the app. wdyt?
- currently, we show all sections in the matches even when there are no results for that section. Maybe it's better to not show that section at all? For instance, if there are only matches for insights, at the moment people first see three sections of no results. If we do change that behaviour, should it still be as it is on search?

**Comment by fannyBkane** [comment]
> I think having a nav makes sense (also on mobile) because people can navigate back to the page from anywhere in the app. wdyt?
Can you clarify this @asimonw ? Do you mean that having a nav enables people to navigate back to the onboarding screen?

>currently, we show all sections in the matches even when there are no results for that section. Maybe it's better to not show that section at all? For instance, if there are only matches for insights, at the moment people first see three sections of no results. If we do change that behaviour, should it still be as it is on search?
We choose to show the section title even when no results in search, in order to show the categories. 
On the matches page, I think it would be a nicer experience to see the categories only when there are results. I think it would be nicer for search to behave in the same way, as it feels unnecessary content to scan... 

However, to take it step by step, I'd suggest to update the matches page (to show category headers only when there are results displayed), and leave the search page as it is.

How does that sound?

**Comment by asimonw** [comment]
@fannyBkane I mean that people can navigate back to the “choose interest” screen at any point, as long as they don’t have interests yet, as it’s the home screen (and also My Matches). I feel that it would jarring for people to suddenly lose the nav when navigating to this page, like they have landed on a different site.

Having a different behavior for matches and search could work, unless they actually use the same component, in which case it would be easier to evolve them together. @Danwhy are you reusing code for both?

**Comment by fannyBkane** [comment]
>@fannyBkane I mean that people can navigate back to the “choose interests” screen at any point, as long as they don’t have interests yet, as it’s the home screen (and also My Matches). I feel that it could be jarring for people to suddenly lose the nav when navigating to this page, like they have landed on a different site.

Thanks for clarifying! Yes it makes sense.

>Having a different behaviour for matches and search could work, unless they actually use the same component, in which case it would be easier to evolve them together. @Danwhy are you reusing code for both?

Just putting on our rada that we collectively took the decision to show the headers on search. Because we assumed that it gave people a sense of what they _could_ be seeing. But it makes sense to consider search/matches together, and evolve them together.

**Comment by Danwhy** [comment]
@asimonw @fannyBkane We are using the same template for matches and search, so making them behave the same would be easier.

**Comment by fannyBkane** [comment]
That's fine with me @Danwhy @asimonw

**Comment by fannyBkane** [comment]
LGTM @Danwhy @asimonw
