### ISSUE TITLE
Bring all data stores in line with data structure in wiki, or update wiki

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#144]
https://github.com/emfoundation/ce100-app/wiki/Data-structure

**Comment by mk4111** [comment]
@JMurphyWeb, suggestions for the Data-structure for challenges:
* think we need to add an 'org' property (so we can associate each challenge with a primary user and an org)
* really minor but I called the key ```creator``` instead of ```creator_id``` and have already pushed up...
Can I change the above on the wiki?

**Comment by JMurphyWeb** [comment]
My only thought is we have active for users and orgs? I don't mind it being archived though as they seem fairly different.

go ahead and change wiki 👍

**Comment by mk4111** [comment]
Cool - I've just updated the [wiki](https://github.com/emfoundation/ce100-app/wiki/Data-structure)

**Comment by JMurphyWeb** [comment]
@mk4111 I think we can close this issue? Can you just confirm that data structure is correct for all branches you are working on? Please close if so. Thanks!

**Comment by mk4111** [comment]
@JMurphyWeb - I've actually bumped into an issue with handlebars for tags - I'll write up an issue on it after this but to summarise - I've saved the child_tag ID as an _array_ in the format [parent_id, child_index_in_array]. I did this because the checkboxes had to have unique IDs - the current child_id alone is repeated so it was checking the wrong boxes when clicked on. We could keep the current format, and I could pass in the id as {{parent_id}}{{child_id}} in the handlebars, but considering the tags in organisations and challanges will be stored as [parent_id, child_id] format for each tag, I think it would be more consistent to do it that way. What are your thoughts?

If we go with the above, I don't think we will actually need ```parent_tag``` in child_tags anymore

I've also named: ```active``` as ```enabled``` and  ```children_tags``` as ```tags``` as I think they make a little more sense to me - completely opinion-based so happy to talk about it a bit more too!

**Comment by JMurphyWeb** [comment]
hey @mk4111.
Tag structure sounds good. Could you give an example of the 2 tag data structures so we can compare? It sounds like there could be some repetition but maybe I am not picturing it properly.

What is your thinking behind `active`/`enabled`? I do quite like `active` because it ties in with other data structures which is handy for consistency. Also it seems likely that we could reuse some functions which apply to an object using `active` as a key. I haven't looked at them but `toggleActivate` and `initialiseEntry` come to mind as possibly being usable with tags, orgs, people... Happy to hear your reasoning for enabled though.
