### ISSUE TITLE
Sprint 2 Routes

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#150]
When setting up sprint 1 we decided on a set of routes that would serve up our main views. I was wondering if we could do the same here, so we are both working off the same page. When they are finalised we can stick them in the wiki with the others.

**Comment by JMurphyWeb** [comment]
https://github.com/emfoundation/ce100-app/wiki/Admin-view-endpoints

**Comment by mk4111** [comment]
@JMurphyWeb I completely agree - I wasn't too sure of the format I should follow with the tags and challenges routes, so adopted them based on our previous routes - please do let me know if you think it might be better to structure them in a different way! :)

For now though, I'll add the endpoints that I created for tags and challenge cards to the link above. Hope that's ok!

**Comment by JMurphyWeb** [comment]
cool! is it ok if i put them in this issue so we can have a think?

**Comment by mk4111** [comment]
Sounds good - shall I branch off from this issue because I think this refers quite broadly to the endpoints in Sprint 2 (which means we'll have discussions about tags, challenges, and maybe filtering and news cards too)

**Comment by JMurphyWeb** [comment]
No i opened this issue with this exactly in mind :)

**Comment by JMurphyWeb** [comment]
`/challenges/add`

I was just wondering if this would be more like:
`/orgs/2/challenges/add`

Then challenge management for a specific org could be done at:
`/orgs/2/challenges`

Then we could have a `/challenges` to view/browse challenges in general?

**Comment by JMurphyWeb** [comment]
Think it would be really good to have something in place asap for this.

**Comment by mk4111** [comment]
I'll lay out my thoughts on endpoint structure, then comment back on your idea - hope that's ok :)

### Challenges
##### ```/challenges``` (?)
(1) 'GETS' A general view of _all organisations' challenges_
##### ```/challenges/add```
(1) 'GETS' the form through which users will add new challenges .
(2) 'POSTS' the contents of this form, and saves in the DB.
##### ```/challenges/{{challengeId}}/edit```
(1) 'GETS' A pre-filled form with existing challenge information
(2) 'POSTS' Updates the challenge
##### ```/challenges/{{challengeId}}``` (?)
(1) 'GETS' Displays a single challenge? May be useful in the future when solutions can be posted online too.

### Tags
#####```/tags```
GETS' the view of all _parent_ tags. On click of any such parent tag, a list of child_tags becomes visible (initially hidden by CSS).

\* the routes with (?) are ones that I _think_ are not in scope.

**Comment by mk4111** [comment]
So right now, the way that a new challenge is being processed (upon submission) is as follows:

- payload includes the session of the user (that is logged in, and has submitted the form) - this includes the user's id.
- using this, we query redis for that user's profile --> we get the organisation_id from this.
- we query redis for the length of the challenges list (which we use as the challenge-card's id)
- we then process the challenge-card details so that we store all the [necessary info](https://github.com/emfoundation/ce100-app/blob/challenges/server/handlers/add-new-challenge.js#L18), which aligns with the data structure we agreed to in the [wiki](https://github.com/emfoundation/ce100-app/wiki/Data-structure)
- this processed object is now saved in the 'Challenges' list
- the challengeId is then stored in the user profile's challenge array (as originally agreed on in issue #38)
- the challengeId is also stored in the organisation profile's challenge array (also agreed on in issue #38 )

Although that endpoint does make sense, I wonder what the benefit of having ```/orgs/{{orgId}}``` at the beginning of the endpoint is - only because we would have to query for it, prior to serving up the form - which I don't think is a necessary step to serve that view up. 

I think the endpoint follows through with the way in which we have implemented the other routes, but am happy to change it if we do find there is a better alternative!

**Comment by JMurphyWeb** [comment]
some good reading for the morning -> Thanks for doing 👍

**Comment by JMurphyWeb** [comment]
I guess i was thinking of the case where the user clicks add challenge when they are viewing their own org.. But there are different ways of getting to the add challenge card creation page...

At the moment the 'necessary info' doesn't align with the data structure in the wiki.

https://github.com/emfoundation/ce100-app/wiki/Data-structure

The current data structure doesn't have challenges in the people set. It does have creator_id in the challenge cards set, which refers to the the primary user. So either way it needs updating/fixing. I do not know if it is necessary to include any link to the primary user when thinking about challenge cards? From what @asimonw said yesterday, there was no link needed. I wonder if he can confirm/refute? If there is not a need for a link to be held, it seems like we would be doing unnecessary redis queries.

Again _if_ there is no link to a primary needed, then I think `orgs/id/challenges/add` could result in a simpler handler in the sense there would be no need to touch the `people` set in order to find the organisations set.  Happy to go with your endpoint but we need to get the data structure fixed asap.

**Comment by JMurphyWeb** [comment]
@mk4111 is it ok if you finalise this challenge card data set with @asimonw? I only ask because you are working on this feature so have better insight. Just let me know if/when wiki is changed.

**Comment by JMurphyWeb** [comment]
Regarding the routes for tags, which we can add to both a challenge and an org:

```
/orgs/id/add/tags                                   // view to select tags when adding a new org
/orgs/id/edit/tags                                   // view to select tags when editing an org
/orgs/id/challenges/add                        // view to add a new challenge
/orgs/id/challenges/add/tags                // view to select tags when adding a challenge
/orgs/id/challenges/id/edit                    // view to editing an challenge
/orgs/id/challenges/id/edit/tags            // view to select tags when editing an org
```

I think this system is good to minimise redis queries, but bad if @asimonw does not want the challenges too tightly linked to an organisation.

What are you thoughts @mk4111 @asimonw ?

**Comment by JMurphyWeb** [comment]
github.com/emfoundation/ce100-app/issues/150#issuecomment-247259714

I think something like this url is what i am roughly going for.

**Comment by mk4111** [comment]
Morning @JMurphyWeb!

> I guess i was thinking of the case where the user clicks add challenge when they are viewing their own org.. But there are different ways of getting to the add challenge card creation page...

True about different 'ways' of getting to the add challenge card. What were the ways you were thinking of accessing the challenge cards? Will those views display things differently? 

> At the moment the 'necessary info' doesn't align with the data structure in the wiki.
https://github.com/emfoundation/ce100-app/wiki/Data-structure

I've added an additional ```org_id``` key, and we're currently [discussing]( #156) the need for the challenge to be tied to the primary_user so I'll keep it there for now. I'm pretty sure the structure is otherwise there - could you please check and confirm, if not let me know how it doesn't align? Thanks.

> The current data structure doesn't have challenges in the people set. It does have creator_id in the challenge cards set, which refers to the the primary user. So either way it needs updating/fixing. I do not know if it is necessary to include any link to the primary user when thinking about challenge cards? From what @asimonw said yesterday, there was no link needed. I wonder if he can confirm/refute? If there is not a need for a link to be held, it seems like we would be doing unnecessary redis queries.

Perhaps - but I'm not sure if @asimonw said specifically that there was _no link_ needed. From my understanding, because a primary_user is currently the only user that can be associated with a company (as there are no secondary_users), that primary_user will always be creating an issue on _behalf_ of that organisation - so I thought it would be helpful to store both sets of information. I think it would in particular help EMF Admin keep track of who created that challenge card in the instance where primary_users have been dissociated with an organisation, and in the future, when users (primary and secondary) will be able to create challenge cards for themselves and for the organisation.

**Comment by asimonw** [comment]
@mk4111 You make some very good points in that final paragraph. I just answered in #156 that there is no direct link needed because there is an indirect link through the org. But as you said, for several reasons and to make things more future proof, it would be very useful to have a "created by" id stored on the challenge. 

So if that doesn't overly complicate things, I'd go for something like that. Not essential right now, but would be needed in the future.

**Comment by JMurphyWeb** [comment]
Wiki has been updated to represent the new data structure.

Back onto routes for the main views in sprint two... @asimonw do you have a preference/suggestion? Any further thoughts @mk4111 

We are deliberating between: 
```
/orgs/id/add/tags                           // view to select tags when adding a new org
/orgs/id/edit/tags                          // to select tags when editing an org
/orgs/id/challenges/add                     // view to add a new challenge
/orgs/id/challenges/add/tags                // view to select tags when adding a challenge
/orgs/id/challenges/id/edit                 // view to editing an challenge
/orgs/id/challenges/id/edit/tags            // view to select tags when editing an org
```
and

```
/add/tags                           // view to select tags when adding a new org
/edit/tags                          // to select tags when editing an org
/challenges/add                     // view to add a new challenge
/challenges/add/tags                // view to select tags when adding a challenge
/challenges/id/edit                 // view to editing an challenge
/challenges/id/edit/tags            // view to select tags when editing an org
```

**Comment by JMurphyWeb** [comment]
@mk4111 please edit if there is something wrong

**Comment by mk4111** [comment]
@JMurphyWeb - nothing wrong from what I can see, but I'm wondering what the difference between /edit and /add are... /add would _only_ add, but /edit would need to add _and_ remove right?
If so, I wonder if it might make a wee more sense to just have an endpoint called
```
/tags/select
```
where we would compare what tags already exist in the database, and add/remove tags accordingly...

What do you think @JMurphyWeb?

**Comment by JMurphyWeb** [comment]
The endpoints i have offered up were specifically for views.

I think the `/orgs/id/challenges/id/edit/tags` & `/orgs/id/challenges/add/tags` both represent the 'select tag' view.

The /edit and /add correspond to the item you are editing or adding, not the tags.
eg `/orgs/id/challenges/add/tags` represents the view of selecting tags for a newly added challenge, corresponding to the organisation that owns the challenge.

**Comment by JMurphyWeb** [comment]
I think maybe `/orgs/id/add/tags` causes confusion. This is probably not needed as it is only applicable to an admin adding a new org and adding tags to that new org. I don't think that is a requirement so we can leave that one off.

**Comment by JMurphyWeb** [comment]
@mk4111 can you please update the second part of my comment with your idea so we can compare the two sets of view endpoints? I don't think i fully understand how it will work with tags. Thanks

**Comment by asimonw** [comment]
I would also tend to agree with @mk4111. Create and edit views are the same (also for challenges): in one case some fields are populated, in the other they are not. I don't think you need two different end points for that. Did you consider using REST-like routing? It would be handy if we end up using more client side rendering.

Also, just to understand this, are you really generating every single view on the server? Just to draw your attention to this, we were having in mind that a lot of views, especially edit views, would be modal screens on desktop, like here zpl.io/1yMwkV.

You'll need to use Ajax for that. Rather than rendering the full new page on the server, it would require rendering a partial (or simply getting some json data from a REST end point if you'd render on the client).

**Comment by asimonw** [comment]
It would be good to get @nelsonic's view on this as well.

**Comment by JMurphyWeb** [comment]
Here is how we have implemented so far:

`/orgs/add` - an admin adds a new org.
`/orgs/id/edit` - an admin edits an existing org.

The views are pretty much the same, but to me it seems strange to have the url the same for both actions.

For challenges we have both suggested following the same pattern:
`/challenges/add` - a user adds a new challenge.
`/challenges/id/edit` - a user edits an existing challenge.

Although I am trying to ask the question if it is desirable for a user/helpful for developers/useless for both to have:
`/orgs/id/challenges/add` - a user adds a new challenge.
`/orgs/id/challenges/id/edit` - a user edits an existing challenge.

**Comment by JMurphyWeb** [comment]
@asimonw see 161 re REST endpoints.

I am also a little hazy around how the tag adding will work. @mk4111 did i clear anything up or do you have any additional thoughts?

**Comment by asimonw** [comment]
You'll want the org id somewhere in the url anyway right? Otherwise you'll need to send that through as POST data or something. I was mentioning REST because there the difference between create and update is in the HTTP verb and the only difference in url is the id:

Create: POST to .../resource
Update: PUT to .../resource/id

Of course, in an ideal separation of concerns, these only deal with data, not with generating views, so what you're trying to do here is different anyway...

**Comment by JMurphyWeb** [comment]
Wiki needs updating.

**Comment by mk4111** [comment]
@JMurphyWeb - are we good to close this issue? :D
