### ISSUE TITLE
Tag selection

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#151]
Linked to #12 

What's the best way to 'select' a tag? Should we/do we need to use front-end javascript?
Given that we're using handlebars, I think it would be more elegant to minimise our use of front-end javascript. 

Right now, I'm thinking that we could create a 'dropdown', where the dropdown options are permanently open (until closed/user opens up a different parent tag) --> then find a way to select multiple options.

On click of "Select", this information gets sent to the backend, where we will process the tags, and serve them up through handlebars.

@JMurphyWeb and @nelsonic what are your thoughts on this method of implementing tag selection? Do you have any suggestions?

**Comment by JMurphyWeb** [comment]
Minimising front end js sounds good!!

**Comment by asimonw** [comment]
@mk4111 @JMurphyWeb not sure how relevant it is, but for me doing the tag selection in the front-end makes it easier to build in cancel functionality. Note that when the user selects a tag, it is not yet 'persisted'. After the user presses 'select' they're taken back to previous screen, where they can save the challenge or profile. However, if at that point they press cancel, the tags shouldn't have changed. Apologies if this wasn't clear.. it's how our prototype works and the most intuitive way of doing it for the user.

**Comment by JMurphyWeb** [comment]
Client side JS @asimonw ??

What are your thoughts of the heavily styled inputs??

**Comment by asimonw** [comment]
@JMurphyWeb I indeed meant that I would write the handler for the tag select button in client-side JS. Dealing with the cancel button is much easier that way. And you don't want the tag selection to persist anything in the db until the user presses 'save'. All of this is pretty manageable with handlebars (or similar) on the client-side. I'd be worried that if you're not using any templating solution on the client, you'll be too reluctant to look for a client-side solution when it's relevant. Without significant client-side JS it will be very hard to make the app feel "app-like".. Since you're using handlebars already you can probably reuse the same templates on the client, no?

I'm not sure what the purpose of the heavily styled inputs would be, because you're not actually getting any text input. The tags could just be div's or li's with a data attribute holding the corresponding id. They only need click/tap handlers which add the selected tag id to a temporary array (for example) of selected id's. The handler also adds a class which makes the tag look selected. A click on a selected tag would have the reverse effect: remove id from list and remove 'selected' class. That's probably how I would do it if I didn't want to involve heavier frameworks/libraries. But surely not the only way.

**Comment by JMurphyWeb** [comment]
Sorry i meant checkbox inputs.. They perform the exact functionality that we desire for selecting the tags, and the could reduce the use of client-side js.

I agree that if they are unfeasible then client side js is the way to go, but @harrygfox mentioned using checkboxes, which i thought was worth considering.

**Comment by asimonw** [comment]
@JMurphyWeb Oh I see, that's indeed a possibility. It can be tricky to get styling of input elements like checkboxes to work well cross-browser, but you can also use hidden checkboxes and some clever CSS (combination of :checked and the '+' selector) to use the checkbox functionality and again a div or li for the visual component.

**Comment by mk4111** [comment]
@JMurphyWeb and @asimonw - I'm working on this now, and am attempting the 'checkbox' method :) I'll see how it looks on other browsers once that's done! Hope that's ok!

**Comment by JMurphyWeb** [comment]
Good luck!

**Comment by mk4111** [comment]
Thank you :)

**Comment by JMurphyWeb** [comment]
closing question as we have answer.
