### ISSUE TITLE
redis helpers from make changes branch

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#155]
Hi @mk4111 if you wanted to discuss benefits of / strategy for getting redis helpers in here, can we discuss here?

**Comment by mk4111** [comment]
Hi @JMurphyWeb! Thanks for opening this up! 
Given that redis error handling was our main reason for taking the approach to refactor that we decided on at the time, I agree that the redis helpers might not be adding much at all. I also agree that the difference in the number of lines of code isn't so significant (merely ~100 lines), and given that we're using such a small subset of redis commands which mostly don't require any pre-processing, I agree that it probably won't make much of a difference.

I guess the only things I'll really be missing from not having the helpers around is our need to JSON.parse() everything we retrieve from LINDEX and LRANGE commands (which are most of our commands) - I think with the helpers, the number of times we invoked that decreased substantially. Another one is the fact that we no longer needed deconstruction anymore - which could still break the app on some browsers - because we can specify exactly what we want to retrieve; but obviously there are ways around that without the need for helpers. Plus the added benefit of having a tidy redis library appeals to me (although unnecessary for our project).

Let me know if you agree/disagree on any of those points! :)

**Comment by JMurphyWeb** [comment]
@mk4111 I definitely like the thought of not JSON parsing everything! What i found helpful was creating helper functions which accept JSON strings as an argument, process the data and then return either objects or JSON strings depending on the helper.. Some handlers implement this better than others.. The helpers give a good indication:

I am sure these can be improved but they do solve the repetitive JSON parsing..
```

helpers.userTypeRadios = (userString) => {
  // default to primary
  var checkedType = userString ? JSON.parse(userString).user_type : 'primary';
  var userTypes = ['admin', 'primary'];
  var userTypeArr = userTypes.map(type => {
    return {
      name: 'user_type',
      value: type,
      display: type,
      isChecked: checkedType === type
    };
  });
  return { userTypes: userTypeArr };
};

helpers.toggleActivate = (stringifiedData) => {
  var data = JSON.parse(stringifiedData);
  var updated = Object.assign({}, data, { active: !data.active });
  return JSON.stringify(updated);
};

helpers.toggleActivateUser = (stringifiedData) => {
  var data = JSON.parse(stringifiedData);
  var updated = Object.assign({}, data, { active: !data.active, organisation_id: -1 });
  return JSON.stringify(updated);
};

helpers.deactivate = (stringifiedData) => {
  var data = JSON.parse(stringifiedData);
  var updated = Object.assign({}, data, { active: !data.active });
  return JSON.stringify(updated);
};

```

> Another one is the fact that we no longer needed deconstruction anymore - which could still break the app on some browsers - because we can specify exactly what we want to retrieve

How do they affect need for deconstruction? I think i know the helper that you are referring to, but from what i can see the helper does the destructuring functionality for us - if you want to remove destructuring we could have a helper which only does that, which would be super reusable? But im not sure of the need - how does deconstruction break the app on some browsers?

**Comment by mk4111** [comment]
Morning @JMurphyWeb :)

I agree that the _generic_ helper functions are really handy in applying JSON.parse to the stringified object from Redis but I'm wondering if there's a _better approach_ to the way we've implemented that; not all handlers functions use those helper functions, or use those helper functions straight after the DB query, which results in our need to still JSON.parse() our response objects ([e.g.](https://github.com/emfoundation/ce100-app/pull/145/files#diff-57c937a2ebced764bfba2ac8fba67a69R109)). I know it might be a minor point, but I do feel like that process is redundant somewhat. If we can be returning the response as an object (which we do with the redis helpers) it means that we only invoke JSON.parse() once per DB request, we won't need JSON.parse() in the helper functions anymore, and it's _generally_ a more consistent way of getting out and processing our data.

Deconstruction is an ES6 feature which means that it's not _100%_ supported on all browsers. I'm glda you brought this up because I've had a better look, and it seems it's not supported by IE or Safari amongst others - please have a lookie [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility). I know @nelsonic was referring to Fat Arrows of ES6, but I guess that's what he meant by _"it breaks the browser"_ We could indeed have a completely separate generic helper function to do that for us, but then again we could just stick to specifying the keys we want, because at that point, we would already have the entire response object to play with.

**Comment by asimonw** [comment]
@JMurphyWeb @mk4111 relying on any ES2015 feature in the browser is a very bad idea. Most of them have _far from_ 100% support. Why don't you use babel?

**Comment by JMurphyWeb** [comment]
Definitely agree on the first point. JSON parsing everything is a pain, and the helper functions set things up nicely for us to start playing with the data. I stand by what i said in that i'm happy for us to implement them 👍 

Regarding destructuring es6 and arrow functions. I don't see how they can affect the browser since all of this work is being done on the server, which allows for such features. For sure when we have a client side js, destructuring and arrow functions are not a good idea.

**Comment by mk4111** [comment]
Given that we have migrated from Redis to Postgres, I think it's safe to close this issue.

I think that our biggest take away from this issue is that now that we are using goodparts linting, we should stick to this, and that we should always consider the case where we may introduce frontend javascript!
