### ISSUE TITLE
Challenge card data structure

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#156]
Yesterday @asimonw confirmed that challenge cards were linked to organisations as opposed to users. 

Does this mean that we do not need to store a link between the user and the org at all?

Ie
- in the challenge set there would be **no** link to the person who created it, only the org.
- in the person set there would be **no** link to the cards that they have created.

We have been discussing it here: https://github.com/emfoundation/ce100-app/issues/150#issuecomment-247259714

[current data structure](https://github.com/emfoundation/ce100-app/wiki/Data-structure) which needs a bit of an update when we finalise this challenge card -> person issue.

**Comment by asimonw** [comment]
@JMurphyWeb Not sure I understand the question. Of course a primary user is linked to an organisation. It determines their permissions and which contact info to show on the profile.

If you meant, no link between user and challenge, then indeed no direct link needed. They are linked indirectly because a user can only create or edit challenges of the org they belong to.

So the structure is:
* Root: organisation
* Primary user belongs to org
* Challenge belongs to org

**Comment by asimonw** [comment]
Thinking about it a bit more, it could be useful in the future to have a record of who created a challenge, since we might have more primary users per org at some point. Not essential for now though, so if it complicates things, ok to revisit later.

**Comment by JMurphyWeb** [comment]
wiki updated
