### ISSUE TITLE
Filter inactive organisations from primary browse view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#191]
At the moment all organisations show up for primary users.

We should filter out inactive organisations.

@asimonw Should we also filter any currently unattached organisations? ie if they no longer have a primary user or never had a primary user?

**Comment by asimonw** [comment]
@JMurphyWeb Good point. They can just show up without the "contact card." So they would show up in the list, but on their profile, there would be no primary contact info. This case will almost never occur, I expect. But if it does, it might be that we're simply transitioning to a new primary contact and there is no reason to make it look like the organisation is no longer part of the network because of that.

**Comment by JMurphyWeb** [comment]
This is done and in master
