### ISSUE TITLE
admin cannot see deactivated orgs in browse view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#218]
Admin should be able to see active and inactive orgs in browse view.

@asimonw 2 questions for admin viewing challenges:

1. Should they see both active and inactive challenges?
2. Should they see challenges created by an inactive org?

**Comment by asimonw** [comment]
@JMurphyWeb I would say that, because admins control the state (active/inactive) of orgs, they should be able to see challenges by inactive orgs. Because archiving a challenge is done by the primary user, an admin shouldn't easily be able to see challenges that primary users no longer wish to share. So:

1. No, only active ones
2. Yes, both from active and inactive orgs (but again, only active challenges in both cases).
