### ISSUE TITLE
Add logo to Add Org Page

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#277]
@asimonw requested admin can add a logo to an organisation on the "add organisation" view.

Question: I am not sure about moving this functionality into the "add org" as opposed to the "edit org" view. what if the image needs to be updated? with it being a fairly inflexible feature, wanting to change the size or background of the logo seems likely.

Question: At the moment the log can take up any amount of space in it's given square boundary, alternatively we could apply a border radius so that they all apper in a circle as per the wireframes and the default logo. Which would you prefer?

**Comment by asimonw** [comment]
@mk4111 You're right, it should preferably appear in both add and edit. Ideally, it should not be editable by primary users, though. 

It's actually fine to use the same form for both add and edit orgs (that was the original idea), rather than using a different view for add. That probably simplifies things.

Yes, applying border radius would be preferred. I'm assuming that the easiest way to make sure it's a circle is for us to upload square images. Or are you thinking of an automated solution for this?

**Comment by JMurphyWeb** [comment]
@asimonw 
I think it is more flexible if we leave that control up to the person creating/adding the images, if they want a circle, they can ask for it as a .png of a specific size.  However if I restrict it to a circle with fixed border radius, there is a chance that we will 'cut' out an important part of the logo, (for example the leaf on the apple logo) or make the logo unnecessarily small just to fit into our permitted circle.

Happy to stick with border radius if that is what is preferred, I just wanted to let you know the pros/cons.

**Comment by asimonw** [comment]
@JMurphyWeb We understand the pros and cons, but it's ultimately a design decision. It's important to be consistent: all circles or all squares. The main risk is indeed logos needing to be too small.

At least it's definitely not a good idea to have to prepare a circular crop for every new logo, as I'm sure you'd agree. Those days are far behind us since CSS can simply automate that for us. If we decide that some logos are simply too small, we turn off border radius and only need to re-crop those few logos. If we prepare the circles manually, we'd have to re-do every single logo to move to a square design. Automation rules 😄 (until there are no jobs left of course..)

**Comment by JMurphyWeb** [comment]
Ok great. I had not realised that you specifically wanted circles for all logos, in which case i definitely agree that border radius is the way to go.

**Comment by JMurphyWeb** [comment]
relates to #260 #10
