### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#308]
On a fresh deploy (from master to the staging area), the log-in works for:
- Chrome (normal window but not incognito) and Firefox (for both normal and incognito).

A few hours after the deploy, the log-in no longer works on _Chrome_ --> it works fine for Firefox, even after flushing all cookies and cache.

I'm having issues debugging because a) it's not an issue I've had with localhost:3000, b) when I push up console.logs to catch the part that is erroring, the app is re-deployed, so the app goes back to working again...

Might be completely unrelated but when trying to access the contents of redisCloud from cli, I get the following error: ```NOAUTH: authentication required```. I've had a google for this issue, but found little for Node. For Ruby, I've found a few links which describe similar things to [this link](http://stackoverflow.com/questions/34115213/redis-raise-error-noauth-authentication-required-but-there-is-no-password-setti)... It still doesn't explain why it works for firefox, but not chrome though, so might be completely unrelated.

**Comment by SimonLab** [comment]
I'm just starting to have a look at the code but first the tests on my localhost are not running because jsonwebtoken is not a dependency in package.json but we are still using it in the [login handler](https://github.com/emfoundation/ce100-app/blob/787bb83b2a09de80db125ed47aa5cc5b07eb0432/server/handlers/login.js#L2)

**Comment by SimonLab** [comment]
The login issue is linked to how the application managed the cookies. The options on how the cookie is set are define in [auth.js](https://github.com/emfoundation/ce100-app/blob/787bb83b2a09de80db125ed47aa5cc5b07eb0432/server/auth.js#L4-L8):
```
  {
    isSecure: process.env.NODE_ENV !== 'development',
    ttl: 1000 * 60 * 60 * 24 * 30,
    path: '/'
  }
```
The problem is linked to the isSecure property.```isSecure: process.env.NODE_ENV !== 'development'``` will be ```true``` on Heroku and ```false``` on localhost (NODE_ENV is equal to production by default on Heroku). This means that on Heroku the cookie will work only if the http connection is secure so only with https. However Heroku provide both types of connection, http and https, so if a user attempt to login with http the application won't create the cookie but this will work with https.
The solution is to define isSecure to false. isSecure just add a more secure way to manage the cookie (see https://tools.ietf.org/html/rfc6265#section-4.1.2.5) but the application already encrypt the cookie with jsonwebtoken so even if someone manage to get the cookie the person won't be able to access the data in the cookie without the key used to encrypt the cookie. However the only problem is where the person manage to get the cookie then use it to access the application. This situation is unlikely to happen and the cookie still need to be valid (not expired) for that.
When the application is only hosted on an https connection we will be able then to redefine isSecure to true.
Does this make sense? Plese add any thoughts or comments :+1:
