### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#32]
Question: what could be a general approach to error messages when manipulating forms. Happy to take recommendations from the dwyl team. Options could be inline for client-side, lightbox for server-side, ...

---

Todos:
- [x] work out more generic error handling system that can be used app wide consisting of snack bar and indicating which input failed
- [x]  work out exactly which views require endpoints handling --> any POST route
- [x]  implement error handling and style

**Comment by asimonw** [comment]
More generally, information messages (e.g. after saving data successfully) and error messages. @nelsonic If you have a preferred (or easy to set up for MVP) mechanism for doing this, happy to go with that. If you prefer that we mock it up, let us know.

**Comment by nelsonic** [comment]
@asimonw yes, in terms of UI it would be _good_ to get some input for what is desired for placement, font and copy for error messages.

We can use `Joi` (object validation) to _automatically_ display error messages for forms based on the _expected/required_ data type.
example: https://github.com/dwyl/hapi-login-example-postgres#5-run-the-server

**Comment by asimonw** [comment]
@fannyBkane lets look into this in the next couple of days?

**Comment by fannyBkane** [comment]
Lets.

**Comment by fannyBkane** [comment]
https://zpl.io/ZTjXWs

**Comment by iteles** [comment]
@JMurphyWeb @mk4111 Lets take a look through and implement at least some basic error handling?

**Comment by JMurphyWeb** [comment]
@iteles I have added some basic error handling to unsuccessful incorrect password/email at login.
In the error message PR.




However any failure of validation throughout the app throws a fairly big error when really just a snack bar is wanted. 

It would be great to have some input from @nelsonic.

When making a `POST` request, there are 3 main possible places for errors:

- Failed validation
- hoek.assert(..., 'redis error')
- Failure at another point during the handler

For example adding a new challenge, a user could write out a description, but forget to fill in the `title` field. Our validation will throw due to an absent required field. Ideally we would return the user to the 'Edit Challenge' view, with the description still filled in, but a snack bar telling the user they have to enter a title.

In the login handler, we can reply with the login view, an error message and the email address that the user tried to submit.  I was wondering how we could go about getting this sort of functionality when a user fails validation.

Similarly I am not sure how to deal with an error caused by a `Hoek.assert`.

I am going to take a further look into: https://github.com/dwyl/hapi-login-example-postgres

**Comment by JMurphyWeb** [comment]
I have found that failAction is probably the way to solve the validation error problem, looking into the docs and the repo i linked above now..

I think I would still appreciate advice on handling a Hoek.assert error. I guess the desired behaviour would be a generic message like "Sorry, something went wrong" in the form of a snack bar.

**Comment by JMurphyWeb** [comment]
https://github.com/dwyl/hapi-login-example-postgres/blob/master/lib/helpers.js

This file seems to hold a few useful functions that I am aiming to bring into our project.

**Comment by JMurphyWeb** [comment]
Todo before assigning nelson:
- [ ] work out more generic error handling system that can be used app wide consisting of snack bar and indicating which input failed
- [ ] work out exactly which views require error handling
- [ ] implement error handling and style

**Comment by JMurphyWeb** [comment]
<img width="464" alt="screen shot 2016-10-03 at 18 12 11" src="https://cloud.githubusercontent.com/assets/12638261/19046380/fa769444-8994-11e6-891b-caeadd9e05de.png">

**Comment by JMurphyWeb** [comment]
@mk4111 if an admin fails validation, for example leaves the name blank when adding an organisation, the following function is used to generate an error object which is sent to handlebars:
```
function errorOptions (err) {
  return {
    values: err.data._object,
    message: err.data.details[0].message.split('"').join('').split('_').join(' ').split('-').join(' '),
    [err.data.details[0].path]: 'form__input-error'
  };
}
```

Where:

- `values` are the existing input values that the user tried and failed with.  We can input these values into the form so the user doesn't lose all of their text when they fail validation.
- `message` is the Joi error message. `first_name` will get transformed to `First name` for the user's benefit, but I imagine this will sometimes come out looking a bit strange. Should be fine for MVP.
- `[err.data.details[0].path]` is the input `name` that failed validation, and `form__input-error` is a css class that we will add to the relevant input field.


Here is how we can use the error object in handlebars:

```
<div class="container">
    <div class="card card--header">
        <h1 class="title">Add Organisation</h1>
    </div>
    **{{#if error}}
    <div class="snackbar snackbar-error">
      <h1 class="error">{{error.message}}</h1>
    </div>
    {{/if}}**
    <form class="form" method="post">

      <label class="form__label" for="name">Organisation Name</label>
      <input class="form__input {{error.name}}" type="text" name="name" value="{{error.values.name}}">

    </form>
</div>
```
**{{error.values.name}}** will be an empty string so isn't that useful in this case, but i left it in to make it clear how it can be used

I think we can use this system for the more basic views (adding a new org/challenge/person) but i can see it getting slightly more complicated for example when the user is editing, so the function above might end up changing a bit, i wanted to update you on how I was approaching it for now. 

If anything doesn't make sense or you have a suggestion please let me know.

**Comment by mk4111** [comment]
I think I can see where you're going with this, and I'm liking it!

A wee confused about one thing though - do we have an ```error.name```? Is it supposed to be a class? I'm guessing it's so that we can make it green or red depending on the message?

It looks like we'd be able to reuse it for the other error handling - besides Joi validation - too, so I'm really liking that! Awesome work @JMurphyWeb !

**Comment by JMurphyWeb** [comment]
i copied most of the ideas from nelsons hapi example i linked to above.

`{{error.name}}` in this case will become `form__input-error` in handlebars, which is a css class I have created some styles for which gets added to the `input` that failed. There is a screenshot of the result posted above.

A slightly more relevant example: 
in the 'add  challenge view' we can use {{error.title}} and {{error.description}}. Depending on which input field failed the validation, one  will be set to `form__input-error` and the other `''`.  That way the failing input will have a class added, and the input that didn't fail will not have a class added.

**Comment by mk4111** [comment]
@JMurphyWeb - sorry are we still using the object returned from your ```errorOptions``` fn? Not sure where ```error.title``` and ```error.description``` come in... 

I agree that it would be good to display errors, only for the input that's erroring though!

**Comment by JMurphyWeb** [comment]
@nelsonic @mk4111 any thoughts?
I am implementing error handling using failAction and previously, i was placing the fail action functions in the Joi model files.

However this became difficult to do when moving onto the more complicated views which need some data in order to be rendered.  I have now adapted the relevant handlers so that they can handle a validation failure as well as a regular non-failing request, and point the failAction to that same handler. 

It is a pattern i took from the hapi-register-postgress-example.

```
var Hoek = require('hoek');
var helpers = require('./helpers');

module.exports = (request, reply, source, joiErr) => {
  var error = helpers.errorOptions(joiErr);
  var challengeId = request.params.id;
  request.redis.LINDEX('challenges', challengeId, (err, stringifiedChallenge) => {
    Hoek.assert(!err, 'redis error');
    var challenge = JSON.parse(stringifiedChallenge);
    var tagsData = helpers.getTagNames(challenge.tags);
    var permissions = helpers.getPermissions(request.auth.credentials, 'scope', 'admin');
    var options = Object.assign({}, challenge, {tagsData}, permissions, {error});
    reply.view('challenges/edit', options).code(error ? 401 : 200);
  });
};

```

**Comment by JMurphyWeb** [comment]
Update: the relevant handlers are now doubling up as handlers and failAction functions.

Pattern taken from hapi-login-postgress-example code.

```
var Hoek = require('hoek');
var helpers = require('./helpers.js');

module.exports = (request, reply, source, joiErr) => {
  var error = helpers.errorOptions(joiErr);
  var loggedIn = request.auth.credentials;
  var permissions = helpers.getPermissions(loggedIn, 'scope', 'admin');
  request.redis.LRANGE('organisations', 0, -1, (err, stringifiedOrgs) => {
    Hoek.assert(!err, 'redis error');
    var options = Object.assign({}, helpers.orgsDropdown(stringifiedOrgs), helpers.userTypeRadios(), {permissions}, {error});
    reply.view('people/add', options).code(error ? 401 : 200);
  });
};

```
