### ISSUE TITLE
pg transition: get all tags associated with a particular challenge/organisation

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#363]
Question arose when looking into add-tags-to-challenge view (covered in #362) 

At the moment we get all tags attached to a particular challenge in `handlers/select-tags-view.js` line 6, and we process this information lines 12-16.

We need this function so that we know which tags have already been attached to the challenge (in the case that we are editing an existing challenge):

possible function name & api:

`request.pg.tags.getTagsAttachedTo(tableName, challengeId, function (err, tags){});`
where tags is an array of tag ids.

All of this will also apply when we look into adding/editing tags attached to an organisation.

**Comment by JMurphyWeb** [comment]
This is an example of what I had imagined we could do:

```js
var Hoek = require('hoek');
var helpers = require('./helpers.js');

module.exports = function (request, reply, source, joiErr) {
  var error = helpers.errorOptions(joiErr);
  var permissions = helpers.getPermissions(request.auth.credentials, 'scope', 'admin');
  var challId = request.params.challengeId;
  // here we should check that the challenge is indeed editable by this user
  // get the tags attached to a specific challenge

  request.pg.tags.getTagsAttachedTo('challenges', challId, function (err, challTags){
    Hoek.assert(!err, 'error getting tags attached to challenge ' + challId);

    request.pg.tags.getAllActive(function (tagsError, allActive) {
      Hoek.assert(!tagsError, 'get all tags error');

      // if there are tags already attached to the challenge
      if (allActive) {
        // add `selected: true` to each one
        // loop through challTags, add selected:true to each occurrance of that tag
      }
      var options = Object.assign({ parent_tags: allActive }, permissions, {error});
        reply.view('tags', options).code(error ? 401 : 200);
      });
    });
  });
};
```

**Comment by JMurphyWeb** [comment]
Perhaps we can actually have a query that does all of the work for us. The query would have to check which tags are attached to a specific challenge, and add `selected: true` to the correct tags, but return all of the tags.  Then we can format the data to look more like this:
```js
{
  "2": {
  "id_cat":2,
  "name_cat":"Cat 2",
  "tags":{
    "2":{
      "id_tag":2,
      "name_tag":"frank"
    }
  }
  },
  "3":{
  "id_at":3,
  "name_cat":"Cat 3",
  "tags":{
    "4":{
      "id_tag":4,
      "name_tag":"flip"
      "selected": true
    }
   }
  }
}
```

**Comment by SimonLab** [comment]
To recap the hanlder [select-tag-view](https://github.com/emfoundation/ce100-app/blob/master/server/handlers/select-tags-view.js) is used for the endpoint /challenges/{idChallenge}/tags which returns all the tags by category and select the tags which belongs to the challenge:
![select-tag-view](https://cloud.githubusercontent.com/assets/6057298/20483224/d4119fcc-afe8-11e6-83e9-1a866e637054.png)

So on this view we need:
- all the categories
- all the tags sorted by category
- the tags belonging to the specific challenge

Instead of doing multiple requests (getAllActiveTags, getChallenge, getSelectedTags,...) and filter all the data with js, we can indeed create a specific postgres request which get all the tags and define which ones belong to the challenge (the structure you define on the previous comment looks to match this logic). So agree with your [previous comment](https://github.com/emfoundation/ce100-app/issues/363#issuecomment-261927139) :+1: . Let me know if you have any problems with the implementation of this specific functions (which should be on the challenge plugin I think)

**Comment by JMurphyWeb** [comment]
Ok thanks

Given that the following things are true:
- It will be more or less the same for challenges and organisations
- We already have a formatting helper function in the tags system
- I already have a branch on the tags-system with mock-data of a similar structure to ours

Regarding which plugin to put the function, would it make sense to build this function on the tags-system plugin?

**Comment by SimonLab** [comment]
If the application is going to use a more abstract function like you describe previously:
```
 request.pg.tags.getAllActiveTagsHighlightingThoseAttachedTo('challenges', challId, function (err, allTags){...});
```
And if this function can be applied to other elements (organisations) then yes we can create this function in the tags-system plugin.

**Comment by JMurphyWeb** [comment]
Ok I am going to write this issue up in tags-system. Thanks for your input @SimonLab 😄

**Comment by SimonLab** [comment]
resolve on the challenges plugin
