### ISSUE TITLE
Disabling a primary user as a side effect of disabling an organisation

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#422]
This was not covered in this issue #418 and this PR https://github.com/emfoundation/ce100-app/pull/421

If the organisation has an active primary user linked we also want to disable the linked user AND disable their sessions.

@asimonw could you confirm this is desired functionality please?

**Comment by asimonw** [comment]
@JMurphyWeb Yes that sounds good!

**Comment by JMurphyWeb** [comment]
@simonlab I dont think this is implemented yet?

**Comment by SimonLab** [comment]
@JMurphyWeb No I don't think either that's why I add the in-review tag to remind us to have a look at it. This should be too comlicated to implememt:
- add a new function in the people plugin which toggle the active property of people belonging to a specific organisation.
- on the handler on the application, once the organisation is inactive, trigger the new created function

**Comment by JMurphyWeb** [comment]
@SimonLab Marie is away right now, but i am sure she was looking into this issue on Friday. Can you confirm?

**Comment by SimonLab** [comment]
@JMurphyWeb yes I think @mk4111 started to work on this issue

**Comment by mk4111** [comment]
Sorry for the late confirmation, I am indeed working on this :)

I have a very basic query string (actually comprised of two queries), that works for this, but am trying to see whether I can switch this out with a `TRIGGER` and a `PROCEDURE`.

**Comment by mk4111** [comment]
I currently have the following:

```js
module.exports = function (id) {
  var procedure = [
    'CREATE OR REPLACE FUNCTION toggleOrgUsers()',
    'RETURNS TRIGGER AS $updateOrgUsers$',
    'BEGIN',
    'UPDATE people',
    'SET active = NOT people.active',
    'WHERE org_id =' + id + ';',
    'RETURN NEW;',
    'END;',
    '$updateOrgUsers$ LANGUAGE plpgsql;'
  ].join(' ');

  var trigger = [
    'CREATE TRIGGER toggleOrgUsers',
    'AFTER',
    'UPDATE ON organisations',
    'FOR EACH ROW'
    'WHEN OLD.active IS DISTINCT FROM NEW.active',
    'EXECUTE PROCEDURE updateOrgUsers()'
  ].join(' ');

  return procedure + trigger;
};
```

`procedure` seems to be recognised and 'accepted' on cli, but the trigger still needs to be tweaked. 

I've realised that there are two things I need to consider:

- Where should this query string be triggered? Because it's a trigger, I assumed it only needed to be invoked at the start, when the database is getting initialised so that the tables know when and how to 'react' to each other; there is however an issue here, which brings me onto the next point.
- We currently rely on updating a specific row by injecting the ID of the organisation into the query string. If we set the trigger on database initialisation, we won't have the necessary information to construct the necessary query _if we follow through with this format_ `>>` with this format, we would need to update, replace and invoke the trigger for every row update, which almost defies the point of having a trigger...

Going to spend a pommy now trying to figure out how to structure a TRIGGER and PROCEDURE _without_ having to specify orgId or peopleId.

**Comment by mk4111** [comment]
From what I can understand, the orgId can be _implied_ through `NEW` and `OLD`, so do not need to be explicitly stated. By specifying `FOR EACH ROW`, we specify a 'row-level trigger', so `procedure` will have the information of the row on which the trigger is being operated. (I think)

**Comment by mk4111** [comment]
Seems to work! :tada:

![screenshot from 2016-12-21 09-58-21](https://cloud.githubusercontent.com/assets/13470325/21384857/292a096c-c764-11e6-9a86-770da6383a27.png)

![screenshot from 2016-12-21 09-54-18](https://cloud.githubusercontent.com/assets/13470325/21384908/4ee68e82-c764-11e6-915d-26faf796dc04.png)

![screenshot from 2016-12-21 09-58-40](https://cloud.githubusercontent.com/assets/13470325/21384876/33864b28-c764-11e6-8f0a-0161f8267f91.png)

**Comment by mk4111** [comment]
Now working on extracting the tests and query out of node_modules, and inputting them into the people plugin, will then add tests to the app, to check for auth.

**Comment by mk4111** [comment]
Need to update mockdata to include:

- active org/active user
- active org/no user
- active org/inactive user

- inactive org/active user
- inactive org/no user
- inactive org/inactive user

combinations for testing the query.

**Comment by mk4111** [comment]
On reviewing existing organisations, existing users, and existing relationships, I can see that I can reduce the list above to work with the following:

- active org/active user `>>` 1/3 
- inactive org/no user `>>` 7/- (Check toggling for reverse too)
- inactive org/active user `>>` 8/11 (Check for reverse for this too)

**Comment by mk4111** [comment]
Tests were passing locally, but kept failing on TravisCI.
It was to do with the fact that the triggers could not be created at the same time as initialising the table and adding in the mock data. Interesting bug! :beetle:

**Comment by mk4111** [comment]
Now updating tests on ce100 app to reflect changes to org toggling

**Comment by JMurphyWeb** [comment]
this should be done when 510 is merged
