### ISSUE TITLE
validation on tags query params and regex in tests

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#424]
Following @SimonLab 's comment on PR [#404](https://github.com/emfoundation/ce100-app/pull/404#pullrequestreview-11562166), we need to establish a few things:

- Add validation on tags query parameter (we don't want to query pg with a wrong/non-existent id type) #425
- On the note of enhancing tests, what is everyone's thoughts on using regex? #427

**Comment by JMurphyWeb** [comment]
@mk4111 these should be 2 issues, otherwise it could end up being open for a while. 

- Agree validation should be added with the PR and it should be tested for in ce100 application.
- I don't see the need for regex in tests as it is being used atm. indexOf is less to write and less to think about and has the same result.

**Comment by SimonLab** [comment]
Agree @JMurphyWeb @mk4111 could we split these issues :+1:

**Comment by mk4111** [comment]
Have separated into two different issues. Will thus close this one! :octopus:
