### ISSUE TITLE
naming of different add tags views

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#429]
Do we have different way of referring to:
 - the add tags to an organisation/challenge 
 - compared to the add tags to browse view?

It seems to cause some confusion and would be useful if we were on the same page. I seem to remember a discussion in Portugal, but thought the outcome was add-tags and select-tags?

requested here https://github.com/emfoundation/ce100-app/pull/428#pullrequestreview-11635239

**Comment by mk4111** [comment]
@JMurphyWeb - Are we talking about how we refer to the handlers? 
If so I agree, I think we did come to that conclusion too.

Just to be triply explicit:
- `add-tags.js` for _adding_ tags to orgs/chals (endpoints: /challenges/{id}/tags and /orgs/{id}/tags)
- `select-tags.js` for _selecting_ the filter tags on orgs/chals (endpoints: /challenges and /orgs)

Good to get this documented/in an issue though - does clear up the confusion we've recently bumped into with this! :christmas_tree:

**Comment by mk4111** [comment]
@JMurphyWeb sorry I didn't realise you were referring to issue428 in the question you asked
You're right `add-tags` I think is ok, but I thought perhaps `selecting` might be a better word because we use that view to also edit-tags right?

But I realise that `select` is then not a good choice of word to use in the browse views, so we could perhaps have the following combinations for `add/edit view` and `browse view`?

- `select-tags` and `filter-by-tag`
- `add-edit-tags` and `select-filter-tag`

What are your thoughts on this? Happy to keep them as they are for now, and change them later if/when they become confusing again!

**Comment by JMurphyWeb** [comment]
I am happy to close this for now and stick with the current naming convention of add tags and select tags.

**Comment by JMurphyWeb** [comment]
Ill leave decision up to you though as you requested the change in the first place.

**Comment by mk4111** [comment]
Cool, we can close for now and reopen if/when necessary
