### ISSUE TITLE
admin create new organisation view

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#46]
linked to #8

- [x] route
- [x] check permissions
- [x] serve basic page
- [x] inputs: title, logo, ~~primary user email address (possibly drop down)~~
- [ ] images will need to be stored in AWS S3 --> See issue #55
- [x] submit button
- [x] route 
- [ ] ~~db check the primary user exists~~
- [x] db add organisation 
- [ ] ~~db update  primary user organisation field~~
- [x] response success/ error

@nelsonic if the images are to be uploaded/saved would you recommend we use AWS S3?

**Comment by asimonw** [comment]
@JMurphyWeb The editable fields (title, logo, primary user) are correct, but I would reference the user by id. I suggest pulling out the list of all users in a drop down. The value could just be the id, but you display the email address. Doing everything based on id makes it possible to easily change how we refer to a user in the UI (e.g. if we decide to add first and last name later on). The only thing you'd need to store in the org model about the related user is its id. Check with @nelsonic whether he agrees with this approach.

**Comment by JMurphyWeb** [comment]
Absolutely. I meant purely from a UI perspective. I have updated task list.

**Comment by mk4111** [comment]
@asimonw will the images be uploaded as urls or as files (i.e. will they be hosted on a separate server or will we need to set up AWS to store these)?

**Comment by mk4111** [comment]
Once we know how the images will be uploaded, we will be able to timebox this and thus see whether we can put this into the Sprint 1 milestone

**Comment by asimonw** [comment]
@JMurphyWeb @mk4111 As discussed, they will be uploaded and should be stored on AWS.

**Comment by mk4111** [comment]
We timeboxed this issue _excluding_ the AWS S3 set up, which we estimate to take 4 hours. So we envisage this issue to be completed in approximately T1.5days

**Comment by mk4111** [comment]
@asimonw the option to add a primary user at this stage has been removed, as we think the user flow becomes complicated if we - at this user flow stage - try to add a primary user (for whom there is no entry in the database), as it would mean that when creating the primary user's account.

We think that adding the organisation (without involving details of a primary user) and then adding a primary user provides a cleaner flow as the organisation - to which the primary user can be associated with - can be selected from a dropdown menu of existing organisations. After the primary user is added, the organisation account is also updated with the primary user's id.

If we followed through with our original plan to (a) specify the primary user on creating the organisation account, and (b) specify the organisation, on creating the primary user account, there may possibly be cases of mis-spelling organisation names / primary user emails which would in turn mean that admin would need to take extra steps in order to fix an error as such, which we think can be avoided if we choose to add an organisation without specifying the primary user.

Please let us know your thoughts! We are keen to make this experience as smooth as possible for EMF, but we realise that this decision was made with little discussion and are happy to change/improve it too. :)

**Comment by vicky-d1** [comment]
@mk4111 For an organisation to be notified of things such as matches, or requests to affiliate with them as a primary user would the org need an email address, which at this stage would be the primary users anyway? In your proposed scenario until a primary user has affiliated with an org would the org receive notifications? Would there be an approval process when requesting to affiliate with an org as a primary user and how would this work? Would org profiles be set up by an admin if they aren't set up by the primary user? 

Very happy to go with your suggestion if it makes more sense but just want to understand how this would work.

**Comment by JMurphyWeb** [comment]
@vicky-d1 in case it isn't clear here is the basic flow:
Admin sets up an organisation. Admin then sets up a primary user and "attaches" them to that organisation. 

It could make sense to hide any "unattached" organisations from the other users of the app as there would be so little information on their page?

**Comment by vicky-d1** [comment]
@JMurphyWeb Thanks for clarifying - that makes sense at this stage when we have 1 user per org.

**Comment by vicky-d1** [comment]
@JMurphyWeb we will update the designs for the admin view of +orgs (zpl.io/1WUXfN) & +user (zpl.io/Z2bByBq) to reflect the change. For +org we will remove the user field, for +user we will remove primary user tick box and include an org drop down list to choose from @fannyBkane

**Comment by JMurphyWeb** [comment]
@vicky-d1 I don't think there are any real negatives except the admin loses a bit of flexibility in terms of the order that they must create new orgs and users, which shouldn't be a problem at this stage.  In general the more rigid that we make the admin's flow, the less time we have to spend on it. Worth remembering that most of these things will be able to change further down the line. Thanks for update on wireframes.

**Comment by asimonw** [comment]
@mk4111 @JMurphyWeb Since further down the line we will be creating more new users than new orgs and your proposal does make it a bit easier for an admin to create a new user and then assign them to an existing org, I agree with the new scenario.

I didn't see any risk for mis-spellings in the original scenario though.. the admin would never type in the name of the corresponding user, but select it from a list pulled from the db. (The original scenario did require the user to be created first.) The only downside is that an admin won't be able to "bulk assign" users to an org, but that's not essential, especially not at this stage.

Are you still storing both the org as a prop of the user AND the list of users as a prop on the org? Does this imply that in the new scenario, when an org is assigned to a user, the org object is also updated with a new list of users? That might still be useful for more efficient rendering.

**Comment by JMurphyWeb** [comment]
deployed
