### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#5]
As a primary user, I can login to the platform, so that I can access and edit my profile.

**Comment by JMurphyWeb** [comment]
Adding 'admin' label as we will use this view for both primary users and admins

**Comment by JMurphyWeb** [comment]
@asimonw can you please let us know if there is anything you are not happy with, or close the issue if not. Thanks

**Comment by asimonw** [comment]
@JMurphyWeb I didn't close this yet because it was hard to test conclusively with the data disappearing from the db every time.

Related to this: In the mockup there are two extra features
* Forgotten password
* Remember me

Perhaps better to create separate issues for this? I think the "Forgotten password" might already be covered somewhere else as it's related to password reset (from the settings #29 ).

"Remember me" would only be priority 3 (although the session cookie should expire less quickly, maybe after a day, until we build this in).

**Comment by JMurphyWeb** [comment]
Forgotten password is covered in https://github.com/emfoundation/ce100-app/issues/7

I think you are right, remember me is issue worthy. I think that if you are unhappy with the current default expiry date of the cookie (currently 30 days), that is probably another issue as well. If/when you make them @asimonw could you please link them back to this so that we know why this issue is not closable?

**Comment by asimonw** [comment]
@JMurphyWeb You're right about forgotten password. I'll create a new issue with lower priority for remember me and close this issue.
