### ISSUE TITLE
Insights/resources: show green/red status dots for admins

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#645]
Admin users can see whether an insight (in Explore -> Insights) or a resource (in burger menu -> Resources) is active or inactive by a green or red dot, respectively, on the left of the title. See the People screen for visual design.

**Comment by JMurphyWeb** [comment]
- [ ] Add css to the insight card partial
- [ ] Update the function to get resources so that we can get both active only and inactive/active

**Comment by mk4111** [comment]
Updates - as the view is similar to People List, the classes have been unified so that each item is a .list__item, and within it, has .card properties.

Now looks like this:

![screenshot from 2017-02-16 21-47-50](https://cloud.githubusercontent.com/assets/13470325/23042841/24ba7352-f492-11e6-8cdd-19bfb471c424.png)
![screenshot from 2017-02-16 21-49-40](https://cloud.githubusercontent.com/assets/13470325/23042846/2745597a-f492-11e6-8109-9c50d969fa60.png)

and for admin:

![screenshot from 2017-02-16 21-49-20](https://cloud.githubusercontent.com/assets/13470325/23042854/30a224bc-f492-11e6-8598-6684d631e5ca.png)
![screenshot from 2017-02-16 21-49-03](https://cloud.githubusercontent.com/assets/13470325/23042851/2f12d4a2-f492-11e6-94ee-130743173aa2.png)

**Comment by mk4111** [comment]
This issue was covered in conjunction with #689
