### ISSUE TITLE
Views - Challenge Details

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#664]
Link: https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c9d044a08e9d20c773338

![screen shot 2017-02-13 at 12 28 38](https://cloud.githubusercontent.com/assets/12638261/22883444/34b373e6-f1e8-11e6-93e6-b4948349036e.png)

Mainly work on the 'suggested matches' partial

**Comment by mk4111** [comment]
@fannyBkane we don't have an example of this in the wireframes but do we want suggested matches to be listed? Or for them to just display to the left instead of the center?

The former option would display the suggested matches like that in your wireframes, and the latter option would look like this:
![screenshot from 2017-02-14 17-34-20](https://cloud.githubusercontent.com/assets/13470325/22941073/fd5429fa-f2db-11e6-80fc-da53d955fc9f.png)

Just wanted to check!

**Comment by fannyBkane** [comment]
Hi @mk4111 I think listed (one org per line) works. Thanks you!

**Comment by mk4111** [comment]
Thank you @fannyBkane !

**Comment by mk4111** [comment]
Updated page now looks like:

![screenshot from 2017-02-14 19-08-02](https://cloud.githubusercontent.com/assets/13470325/22944563/033c2dd8-f2e9-11e6-826a-0c2e7b3cfd50.png)
![screenshot from 2017-02-14 19-08-14](https://cloud.githubusercontent.com/assets/13470325/22944566/058f7716-f2e9-11e6-919b-43e734c6c5ef.png)

**Comment by mk4111** [comment]
Updated views with correct font now looks like:

![screenshot from 2017-02-14 20-21-27](https://cloud.githubusercontent.com/assets/13470325/22947872/6ce45e94-f2f4-11e6-8760-b234c4e076ac.png)
![screenshot from 2017-02-14 20-27-57](https://cloud.githubusercontent.com/assets/13470325/22947878/6feebe72-f2f4-11e6-8fec-7d46aef905ce.png)

**Comment by mk4111** [comment]
Now back to fixing this issue after fixing a few complications in #661...

**Comment by mk4111** [comment]
Tried to play around with display:inline-block/inline, padding/margins on the icon + challenge-header, but it does not seem to be particularly effective...

Have set width of challenge header to 95% instead as a fix.

**Comment by mk4111** [comment]
The result is as follows:

Primary user of org, with permission to edit own challenges:
![screenshot from 2017-02-15 13-34-11](https://cloud.githubusercontent.com/assets/13470325/22977079/2fa46290-f385-11e6-8269-9a304044d8f0.png)
![screenshot from 2017-02-15 13-34-31](https://cloud.githubusercontent.com/assets/13470325/22977084/32091a1c-f385-11e6-85f0-a9d535fed5d0.png)

Removing a letter from 'with' so that we are one letter shorter gives us this view:
![screenshot from 2017-02-15 13-36-04](https://cloud.githubusercontent.com/assets/13470325/22977109/48b82a78-f385-11e6-9152-d63e03664dab.png)
![screenshot from 2017-02-15 13-35-20](https://cloud.githubusercontent.com/assets/13470325/22977106/456bb18c-f385-11e6-8822-54d604998108.png)


From the public (e.g. secondary users), the challenges look like:

![screenshot from 2017-02-15 13-40-03](https://cloud.githubusercontent.com/assets/13470325/22977123/59719020-f385-11e6-86b1-2c8ec9f63fd5.png)
![screenshot from 2017-02-15 13-40-17](https://cloud.githubusercontent.com/assets/13470325/22977130/5d81f9a2-f385-11e6-988f-9bbd6275656a.png)

**Comment by mk4111** [comment]
Need to fix tests!

**Comment by mk4111** [comment]
...might be because I altered the details of challenge 3 in node_modules. reinstalling!

**Comment by fannyBkane** [comment]
@asimonw fine to close.
