### ISSUE TITLE
Views - Explore Orgs

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#666]
Link: https://app.zeplin.io/project.html#pid=589c772f8ad534321d652f04&sid=589c895039daf1ba0cd194ec

View:
![screen shot 2017-02-13 at 12 45 43](https://cloud.githubusercontent.com/assets/12638261/22883952/62c0971c-f1ea-11e6-8412-adff980bfd9a.png)

**Comment by JMurphyWeb** [comment]
I actually think this should be fixed with the change to the `border-bottom` of the `.card` class

**Comment by mk4111** [comment]
Hi @JMurphyWeb - it isn't changed; I opened a new issue #681 for this, as it does involve a number of classes. If we remove border-bottom from .list__item, we will need to make changes to partials/user.html too, as this relies on .list__item having a border-bottom (but I think that might be fixed with replacing with .card instead)

**Comment by mk4111** [comment]
Have made the relevant changes which affect the user.html partial in #697.
The things that affect organisation explore view are the padding/margin settings on `.list__item`.

View now looks like:

![screenshot from 2017-02-20 13-35-19](https://cloud.githubusercontent.com/assets/13470325/23127063/7093aa82-f771-11e6-864c-734564b6563b.png)

**Comment by fannyBkane** [comment]
@mk4111 Ace. 
@asimonw fine to close this one.
