### ISSUE TITLE
Feedback widget sits on top of bottom nav

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#770]
in mobile view, the feedback widget blocks the bottom nav:
<img width="190" alt="screen shot 2017-03-06 at 15 08 38" src="https://cloud.githubusercontent.com/assets/12638261/23611220/e22ba2a4-027e-11e7-9e01-aa8f8ac549b3.png">

adding some styling to the following id:
`id="intercom-container-body"`
something like:
`transform: translate(2rem, 2rem);`

**Comment by JMurphyWeb** [comment]
@iteles not sure where to put this issue.

**Comment by asimonw** [comment]
@JMurphyWeb Thanks for logging this. We've noticed it and @fannyBkane will look into whether the plugin has some config option to position the widget.

If not, we'll need to either remove the widget or revisit the design, none of which would be something you need to look at for this sprint.

**Comment by JMurphyWeb** [comment]
transform: translate(1rem, -3rem);****

**Comment by JMurphyWeb** [comment]
@mk4111 this should do it

**Comment by asimonw** [comment]
@JMurphyWeb You mean you're manipulating the widget positioning on your end? If that solves it, great!

**Comment by JMurphyWeb** [comment]
yeah it looks ok
 👍

**Comment by mk4111** [comment]
@JMurphyWeb - seems that even when the above is added to main.css, it's overridden by the settings set by Intercom. Might not be a fix that's as straightforward as we originally thought...

**Comment by SimonLab** [comment]
The position of the icon is better with the merged PR #773, however now the intercom box seems smaller (which might not be an issue):
![small-intercom](https://cloud.githubusercontent.com/assets/6057298/23632796/2e706dd4-02bb-11e7-8d74-2f59412f89e8.png)

But now the chat box popup doesn't show properly on mobile (android), just a light shadow appears but nothing else.

We can rollback the last PR (#773) to have a functional intercom on desktop and mobile but with original position for the icon. Otherwise @JMurphyWeb @mk4111 do you have an idea how to fix it?

**Comment by mk4111** [comment]
@SimonLab; I'm seeing exactly the same thing. 
Mobile (Android; Chrome) - not working.
Desktop view - working.

**Comment by asimonw** [comment]
@mk4111 We can look into attaching Intercom to a custom element in the app. Here's an outline of how to do it https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customize-the-intercom-messenger-technical

We'll need to revisit this for a later sprint, because it might require @fannyBkane to design a custom button. This is also an opportunity to make something which fits the style of the app more.

**Comment by sohilpandya** [comment]
@fannyBkane @asimonw have we thought of where we would like this to be implemented as a custom element in the app?

**Comment by asimonw** [comment]
@sohilpandya On desktop it can stay where it is, but on mobile, we'd like to have it sit right above the bottom nav, with some comfortable padding of course. Horizontal position can stay the same. @fannyBkane isn't in today to advise on the padding, but happy to get @harrygfox 's input as well.

**Comment by asimonw** [comment]
Sorry to re-open this, but we've just realised that the Intercom widget still sits a bit uncomfortably when opening the tag selection modal on mobile:
<img width="379" alt="screen shot 2017-05-24 at 16 48 38" src="https://cloud.githubusercontent.com/assets/15235804/26412592/2adda79e-40a1-11e7-9b64-1d3cf083b3e5.png">

Would it be possible to simply hide the widget underneath the modal by giving the modal a very high z-index?

**Comment by sohilpandya** [comment]
@asimonw that's ok, unfortunately increasing the z-index does not move the feedback icon to the back, probably because it's an iframe. 

Do you have any other solutions in terms of how would like to lay it out?

**Comment by asimonw** [comment]
@sohilpandya If that's too complicated, it's fine to leave the position of the widget as it is.
On some mobile screen sizes, however, the buttons stack instead of sitting next to each other. Could you make sure they always sit next to each other? Otherwise, the position of the widget is a bit too jarring.

For instance, here's what happens on iPhone 5 and 6 (iPhone 6 Plus is OK)
<img width="390" alt="screen shot 2017-05-25 at 14 23 51" src="https://cloud.githubusercontent.com/assets/15235804/26451909/d3bbc44a-4155-11e7-8abc-d556cd2ccc73.png">

**Comment by sohilpandya** [comment]
@asimonw I've made the change related to the stacking of the button
Could you please test it on Staging. 👍

**Comment by fannyBkane** [comment]
@sohilpandya @asimonw LGTM 👍
