### ISSUE TITLE
Add hover states

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#797]
Details to be added

**Comment by fannyBkane** [comment]
Hover states are 10 % darker value on links and buttons across the site.

Except for: nav links and tabs links on the 'explore' screen, which has a different hover state: 
a 10% darker overlay, and the active state is the same as hover but less the overlay
https://zpl.io/gFBqs

**Comment by harrygfox** [comment]
@SimonLab @sohilpandya  The hover states require the UI to be able to distinguish between the apps roots: it needs to know when it's on `/orgs` and apply the correct CSS modifier class to the right element. 
In other partials this has been done with handlebars logic, but I don't know how to do it for this app.
The relevant class (which is already in main.css at line 1472) is `navbar-top__item--active-border`

**Comment by SimonLab** [comment]
@harrygfox this should be fixed now. I've added some state on the backend which allow use to determine which page type has been loaded ("explore" "add challenge" "profile" or "add").
@harrygfox @sohilpandya @Jbarget could  you check the PR linked to this issue, thanks #813

**Comment by harrygfox** [comment]
@SimonLab I thought the desired behaviour was that when the user clicks on 'Explore', for example, the Explore "tab" in the top navigation bar remains highlighted until the user navigates away to some other part of the app. 
_This is currently the behaviour in the "togglebar" (containing: Orgs, Challenges, Insights)._ 

Am I wrong @asimonw @fannyBkane ? 
If so, then this Issue is concluded (depending on acceptance test).
If not then this needs more work

**Comment by harrygfox** [comment]
Sorry @asimonw @fannyBkane please disregard the message above, I had my wires crossed!

**Comment by asimonw** [comment]
@fannyBkane @harrygfox I don't seem to see any discussion around hover states for tags. I think the 10% darker rule would also be really useful here.

**Comment by fannyBkane** [comment]
@asimonw agreed. @harrygfox could you add the 10% darker rule on the tags?

**Comment by SimonLab** [comment]
@fannyBkane we just added 10% darker background, let us know if this is ok :+1:

**Comment by asimonw** [comment]
@SimonLab @fannyBkane I can only see the hover effect on tags with a white background. Tags which appear on profiles and challenge cards (with dark background) should also have a hover effect, because they are also clickable (and navigation items).

**Comment by fannyBkane** [comment]
Hey @sohilpandya  I realised that 10 % darker value hover states had not been implemented across the whole site. My bad. Could you look at the elements on the pages below and amend? I hope it makes sense. Thank you!

- Links, Add challenge button, tags, edit button: https://staging-ce100-emf.herokuapp.com/orgs/1

- Links, tags, edit button: https://staging-ce100-emf.herokuapp.com/challenges/3

- Save and publish button
https://staging-ce100-emf.herokuapp.com/challenges/add
https://staging-ce100-emf.herokuapp.com/challenges/3/edit

- Filter icon (blue background) and background of list items: 
https://staging-ce100-emf.herokuapp.com/orgs

- Menu links in burger on desktop

- Links and Save button: https://staging-ce100-emf.herokuapp.com/people/3/edit

- See more icon, and background list item https://staging-ce100-emf.herokuapp.com/people

- Could you remove the blue underline from the three dots in the main nav on desktop and replace by a 10% darker hover state?

- Could you remove the underline of links and turn them to the grey #40667e, with a 10% darker value hover state, so that the links are consistent across the site https://staging-ce100-emf.herokuapp.com/challenges/3

**Comment by sohilpandya** [comment]
@fannyBkane I'll look into the above now. 👍 Hope you don't mind that I've converted them into a checklist. 😊

**Comment by sohilpandya** [comment]
@fannyBkane could you please explain the following item from the list above:

> Filter icon (blue background) and background of list items:
> https://staging-ce100-emf.herokuapp.com/orgs

I'm unsure what you mean here. I've updated the rest of the things and will update the label to please-test once it's been pushed to staging for you to test.

**Comment by fannyBkane** [comment]
Hey @sohilpandya As a hover state, Considering the icon was already dark, could the blue background change to 10% darker?

**Comment by SimonLab** [comment]
@asimonw @fannyBkane a new version has been deployed do you mind to have a look and to give us your feedback? Thanks

**Comment by fannyBkane** [comment]
I've noticed that the challenge link hover state blends with the backgrounds on mobile/profile and small viewports - not sure it is a problem considering there is no hover state on mobile but it would be great to hear your thoughts on that: would it be better to change the hover state to a lighter colour on small screen anyway, in case?

On a different note it looks that the archive link is shown twice.

![screen shot 2017-05-24 at 15 44 22 2](https://cloud.githubusercontent.com/assets/20577339/26409316/1fd444d8-4098-11e7-9d6b-b1e580982cfc.png)

**Comment by sohilpandya** [comment]
@fannyBkane I've made the change related to the hover color for the smaller devices and happy to push those up for you to test, but could you please tell me the steps you've taken to get to the above screen as I am unable to replicate the `Archive challenges` showing up twice.

**Comment by fannyBkane** [comment]
Hey @sohilpandya awesome. I viewed the app on desktop, made the viewport small.... And did Nav>Profile. On mobile, although you can't really scroll down further down, but if you try, the link shows too.
![img_9131](https://cloud.githubusercontent.com/assets/20577339/26410771/1cb187d0-409c-11e7-9eb9-0cff509c16b6.png)

**Comment by sohilpandya** [comment]
@fannyBkane thanks for that. I've updated this on staging and it should be ready to test again.

**Comment by fannyBkane** [comment]
@sohilpandya looks good, cheers!
