### ISSUE TITLE
Inconsistent avatar sizes 

### ISSUE THREAD

**Issue by Jbarget** [emfoundation/ce100-app#874]
On the list of organisations the avatar is a rectangle, however on the individual org page the avatars are circular

See screenshots below:

![screen shot 2017-05-18 at 15 25 00](https://cloud.githubusercontent.com/assets/11725595/26689260/01372d6e-46ed-11e7-8a87-1bf987036d35.png)
![screen shot 2017-05-18 at 15 25 08](https://cloud.githubusercontent.com/assets/11725595/26689261/029fbe1e-46ed-11e7-930e-6cb6deb41934.png)

**Comment by asimonw** [comment]
@Jbarget The avatar looks circular in both cases in production. Is there a new local change which makes the avatars rectangular in the list view?

What I have noticed is that the avatar is not properly centred vertically anymore on the profile view since the fallback icon has changed. It's centred correctly with the fallback icon, but not with a user uploaded image.

**Comment by Jbarget** [comment]
@asimonw sorry for late reply,

nothing that I know of, If its not showing up on your side of things then Im happy to leave it for now. (I would say close this issue but it sounds like theres separate bug related to this issue)

**Comment by asimonw** [comment]
Ok @Jbarget I'll close this one. The separate bug is now logged in issue #876.
