### ISSUE TITLE
Issues with tests (and therefore coverage)

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#88]
* Only the first (of 3) tests is run --> coverage percentage is therefore misleading.
* What is the best way to test/mock bcrypt errors? #89 
* What is the best way to test/mock redis errors? #90 
* Make sure that we end redis connection and server at the end of each test file.

**Comment by mk4111** [comment]
#### Redis Errors
With redis-mock, on switching the real redis client with a redis-mock client, the tests began failing where they were not previously. 

#### BCrypt Errors
Have googled for answers but to little avail - if @nelsonic you could help us, we would really really really appreciate it! Thank you!

**Comment by JMurphyWeb** [comment]
Logging error and replying with the error after every redis call suggests we could be doing something better.  If we can find an alternative way of querying redis multiple times, we would have more readable and maintainable code, and we would get a boost in test coverage without any trade off. Promises are the only way i can think of and have opened an issue #87, but maybe there is another way. 

I only bring that issue up here because i hope we do not need to mock redis for each error and i don't want us to waste unnecessary time doing so (although understand it may be needed at times).

**Comment by nelsonic** [comment]
@mk4111 if you still have time to pair on this this evening, let me know!

**Comment by nelsonic** [comment]
@mk4111 please confirm if this is still an issue. if not, please close it. thanks.

**Comment by mk4111** [comment]
@nelsonic - sorry, this is no longer an issue! Thank you!!
