### ISSUE TITLE
API spike

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#889]
As discussed previously, EMFoundation is in the process of creating an API that they wish to interact with the CE100 application.

A 1 day spike is to be carried out on understanding the API and discussing possible changes required based on the integration requirements on Thursday 14th September. 

+ [x] Review API documentation
+ [x] Test API GET requests
+ [x] Determine whether anything needs to be altered or adapted for the CE100 application
+ [x] Determine the changes that will need to be made to the CE100 application itself and time estimate these

**Comment by SimonLab** [comment]
Thanks for the call @asimonw @georgemillard @iteles 
I'lll try to deploy my tests with the api on a specific branch on Github and on ce100-test on Heroku, I'll let you as soon as there is something to test.

The format we used to create an API is http://jsonapi.org/ . It was good to have a standard to follow but it might be worth to see if there is an easier alternative, JSONAPI format feels a bit verbose especially when using filters. At this stage I think we can keep the API simple like describe on your doc :+1: 

I am currently how we get the insights from the Postgres database. We use at the moment the following plugin: https://github.com/postgres-plugin/insights
So I'm looking at removing the call to this plugin and try to add the API calls instead and will filter directly on our backend the data depending on the tags selected:
https://github.com/emfoundation/ce100-app/blob/49594598c36807f882d44b17fc17836aa6fa3077/server/handlers/insights/browse-insights.js#L13-L22

**Comment by asimonw** [comment]
Thanks @SimonLab , regarding the trailing slash: I'm pretty sure that this default can be changed in Django. @georgemillard can you confirm that? 

Regarding the format returned by the API: could you point out the precise differences? We could look at whether it can be changed from our side as well. Since this is the first place where the API will be used, we could consider changing the returned format as long as it's as universal as the current format.

**Comment by SimonLab** [comment]
For example the assets and insights have a slight difference:
**asset**
```
{
  "id":206,
  "name":"asset99","file":"https://...",
  "link":"",
  "description":"asset99 description.",
  "duration":null,
  "creation_date":null,
  "copyright_info":"",
  "enabled":true,
  "status":"",
  "type_field":"LN",
  "filetype":"audio/mpeg",
  "uploaded_at":"2017-09-09T11:04:55.949717Z",
  "last_edit_at":"2017-09-09T21:05:09.949717Z",
  "tags":[4,62,43,25,42],
  "locations":[31,43,64],
  "contributors":[17,12],
  "collections":[1]
}
```
**insight**
```
{
  id: 1,
  title: 'Insight Number 1',
  url: 'https://...',
  author: 'Simon',
  creator_id: 1,
  type: 'REPORT',
  date: 2017-05-30T10:26:20.758Z,
  active: true,
  tags: 
   [ { tag_id: 8, tag_name: 'Agriculture' },
     { tag_id: 1, tag_name: 'Global Partner' },
     { tag_id: 22, tag_name: 'Telecommunications' } 
  ] 
}
```
Our templates already use the format of the insight so it would take a bit of time just to match the format of the API in our html. However I don't think the DAM API should based its response on the way we build our data format. We will still have to do a bit of formatting on our side so I don't think changing the format on DAM side is necessary. We can build some functions to extract the information we need for ce-100 and I think these functions can be updated easily depending on API changes. For example I quickly created a function to convert asset to insight:
https://github.com/emfoundation/ce100-app/blob/ff13c4ff8f66ee6a7d5a62525c58442c4e50d21a/server/handlers/dam-api-helpers.js#L5-L28

If I see some data that I think the API should return I will let you know and we can discuss if it's easy for you to implement. For example the insight format return the tags list with ```tag_id``` and ```tag_name```, the asset format only returns the ```id``` of the tags. I don't think we use the tags on the insight at the moment but instead of doing another DAM API call to get the tags maybe I could suggest for the DAM API insights to return directly the tags. Again this is not a blocker and not something to implement now as I don't need them, it's just to give you an example of the kind of requirement we could have.

**Comment by georgemillard** [comment]
@SimonLab Hi Simon, regarding the trailing slash, I have tested this with Python requests, and Postman, making GET requests of the form /api/assets/<asset_id> (no trailing slash) and have had no problems.

Is this maybe an issue with the Wreck plugin?

Let me know your thoughts - thanks.

**Comment by SimonLab** [comment]
Thanks for testing that on your side @georgemillard I'll check again and see if Wreck is the issue :+1:

**Comment by SimonLab** [comment]
@asimonw @georgemillard do you know what is the database used for DAM? I'm currently looking at postgres replications and try to determine if the synchronisation process could be done directly at the database level.

**Comment by asimonw** [comment]
@SimonLab The DAM database is also postgres. Might help :)

**Comment by SimonLab** [comment]
I think, synchronising the DAM database with the ce100 database is not necessary and we can use the DAM API only (if a few more endpoints are created)
 
# Explore view
- Update the explore insights handler to get the assets via the API
- Update the filter tags page to use the API:
![image](https://user-images.githubusercontent.com/6057298/32597089-7b7668c4-c52d-11e7-888c-e23b02523f36.png)
- fiter insights by tag:
  - Get all the insights and filter on the ce100 side
   **OR**
  - Create API endpoint on DAM which allow the ce100 app to get assets (Insights) filter by tag

# Search view
- get all the assets and search/filter by term on the ce100 side
**OR**
- Create endpoint on DAM to search a term on assets (Insights and resources)

# Create/Edit organisations (same for challenges)
- get the list of tags (without the deprecated tags)
- associate the new org with the selected tag ids

- on edit tags of the organisation, get all tags included the deprecated ones if there are already linked to the organisation

# Create assets
- Create POST API endpoint on DAM to upload assets #1043 

# Tags & Locations
Each time we use tags on the application we need to use the API tags endpoints **AND** the locations endpoint as they are now split in two groups

**Comment by georgemillard** [comment]
@SimonLab The search view raises an interesting point. It wold be good to look into searching via a DAM endpoint, but probably the first iteration will be get all assets and search on the ce100 side.

**Comment by SimonLab** [comment]
This spike has been completed and the DAM API is now integrated on a test app
