### ISSUE TITLE
Search Insights

### ISSUE THREAD

**Issue by SimonLab** [emfoundation/ce100-app#929]
Search through title, author field and tags

Similar to the challenges search #928 the only more complex query is the searching for insights by tags. Ohterwise the search on title and author field can be done easily

**Comment by asimonw** [comment]
I notice that insights that have "Show in resources" enabled don't show up in the search results, even if they have tags (so they do appear in the Insights section of Explore).

I think that this is fine, because in practice we probably won't have any resources which are also tagged, and this flag will probably be removed once we build the integration with our digital asset manager anyway. Just wanted to note this for future testers.

**Comment by asimonw** [comment]
That note aside LGTM.
