### ISSUE TITLE
Dynamically expanding comment box

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#977]
Expanding the comment box using JavaScript as the user is typing. This would allow the textarea field to be only one line high at the start.

The same behaviour should be implemented for editing comments.

**Comment by Cleop** [comment]
**Research notes:**
- First checked if there were any non-js options. Found this option using `<div contenteditable>` : http://jsfiddle.net/gD5jy/. But after experimenting with this determined that to transfer the value of the edited div to the form may require js, it doesn't work if you try to apply the `contenteditable` attribute to a `textarea`. Also had concerns about using a `div` instead of a form component for accessibility requirements. 
- Now moving onto js alternatives...
