### ISSUE TITLE
Styling for flagged comments in edit mode

### ISSUE THREAD

**Issue by iteles** [emfoundation/ce100-app#979]
As an admin,
I would like to see consistent styling throughout the application
So that my experience is not jarring and doesn't feel buggy to less technically inclined admins.

Currently:
<img width="759" alt="screen shot 2017-10-24 at 14 35 12" src="https://user-images.githubusercontent.com/4185328/31946078-bb2ee8fe-b8c8-11e7-9027-d1d2a8d57c00.png">

## Acceptance criteria
+ [x] Background of input box in edit mode is also red as per the rest of the flagged comment
+ [x] Cancel & Save buttons are either fully inside or fully outside of the red area; inside might be clearer (discussed and agreed with @asimonw in sprint planning)

**Comment by asimonw** [comment]
@Cleop Looks pretty good. Just a tiny thing: would it be possible to add some left/right padding to the Save & Unflag button?
<img width="271" alt="screen shot 2017-10-30 at 19 03 34" src="https://user-images.githubusercontent.com/15235804/32218464-38f011c0-be2b-11e7-87c6-0cc928ff8c27.png">
In general, styling things so that the button width scales with the text inside would make sense to me (possibly with a min width).
